### ISSUE TITLE
How to add java language option to show methods?

### ISSUE THREAD

**Issue by saikrishnaradarapu** [Mermade/widdershins#1]
Java is missing in the languages option.. Where to add a language?

**Comment by MikeRalphson** [comment]
Hi @saikrishnaradarapu , thanks for stoppping by! The most flexible way to include Java (or any other language samples) is to include the `x-code-samples` vendor extension in your Swagger / OpenApi specification.

See [here](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#operation-object-vendor-extensions).

Then you would run `widdershins` with the `-c -l` options to turn off the default language samples and automatically generate the list of languages from those contained within the input specification.

That said, I would be very happy to receive a Pull Request to add a generic Java code sample. This would be around lines 108 in `index.js` for the list of languages and around line 244 onwards for the Java sample. Or if you have an example I can add it too.

The plan going forward is to extract out the default language samples and some other sections which are currently hard-coded into editable templates.

Please let me know if you spot any other problems.

**Comment by MikeRalphson** [comment]
@saikrishnaradarapu a default Java code-sample template has now been added courtesy of @rauenzi, please let me know if you're working from a clone of the repository or you'd like a patch release to the npm package.

**Comment by saikrishnaradarapu** [comment]
Yeah Thank you all.. Java Language specification is also working..

**Comment by MikeRalphson** [comment]
@saikrishnaradarapu Thank you for letting us know. Again, if you spot any other problems, please don't hesitate to raise another issue.
