### ISSUE TITLE
Embedding/attaching schemas in request body

### ISSUE THREAD

**Issue by JLNNN** [Mermade/widdershins#101]
Hey,
thank you for this project, it's really useful :)
After reading and trying to understand each issue that could be related to my problem I decided to open another one. Sorry if I missed it if it has already been discussed.

When using widdershins to generate my markdown file and copy+paste this file into the slate directory, I get a nice view of my API. But to check the models for my request bodies, I have to scroll the page down to the area "Schemas". Is there any way of having them "inline" or "attached/embedded" to my API requests, like the guys from Stripe are doing it?

Thank you in advance & for your time,
  Julian

**Comment by MikeRalphson** [comment]
Hi, thanks for the kind words. I wonder if the `--expandBody` option might do what you want from your description?

There should also be a clickable link to the relevant schema to save having to scroll, let me know if that's not working.

Failing that, I will take a look at Stripe's documentation again to see what we can achieve.

**Comment by JLNNN** [comment]
Sadly, ```--expandBody``` is not fitting the requirements for me in this case. Sure, it gives me some more details about the parameters I can add to the request, but it doesn't show me the details about the model like I get when scrolling down to the schemas area.

**Comment by MikeRalphson** [comment]
When you say "the details about the model" - could you expand on what exactly is missing? E.g. type, required, description, example etc?

**Comment by JLNNN** [comment]
Everything that's included in the table under section "Schemas". I'm asking myself if that's easy possible or if that's a "thing" of slate itself.

**Comment by MikeRalphson** [comment]
The schemas tables contain:

|Name|Type|Required|Description|

and when a requestBody is expanded, the parameter columns are:

|Parameter|In|Type|Required|Description|

So I'm afraid I'm still not sure what details are missing. Perhaps an annotated screenshot would help?

**Comment by JLNNN** [comment]
On [this screenshot](https://user-images.githubusercontent.com/1099235/38407467-d39ac85e-3979-11e8-9f2d-4cb718999b61.png) you see some of the operations and how to create a printjob.
And if I scroll down to the very bottom of the page, you'll see the [schemas](https://user-images.githubusercontent.com/1099235/38407657-a65fc622-397a-11e8-90be-534495191213.png).
The problem is that this API is still under development and I am now allowed to post it to the public at the moment 😕

**Comment by MikeRalphson** [comment]
The `any` on your screenshot is still troubling me.

With a `$ref`d requestBody schema and `--expandBody false` I get this:

|Parameter|In|Type|Required|Description|
|---|---|---|---|---|
|body|body|[test](#schematest)|false|none|

With `--expandBody true` I get this:

|Parameter|In|Type|Required|Description|
|---|---|---|---|---|
|body|body|[test](#schematest)|false|none|
|» a|body|string|false|none|
|» b|body|string|false|none|

With an inline `schema`, I get this:

|Parameter|In|Type|Required|Description|
|---|---|---|---|---|
|body|body|object|false|none|
|» a|body|string|false|none|
|» b|body|string|false|none|

Regardless of whether `--expandBody` is set or not.

So without a sanitised example input I can't reproduce this with the current version. Please feel free to chase with any additional information.
