### ISSUE TITLE
oneOf anyOf allOf break response schema table in markup

### ISSUE THREAD

**Issue by simondean** [Mermade/widdershins#103]
Hi.  Using a oneOf/anyOf/allOf in the following way seems to break the response schema table in the Slate Markdown/HTML generated by `shins`.  I've created an example code base in https://github.com/simondean/widdershins-issues/tree/master/one-of-in-response-schema that demoes the issue.  

Here's a simplified version of the response schema I'm seeing the issue with:
```json
{
    "type": "object",
    "properties": {
        "greeting": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "object",
                    "properties": {
                        "message1": {
                            "type": "string"
                        },
                        "message2": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "message1",
                        "message2"
                    ]
                }
            ]
        }
    },
    "additionalProperties": false,
    "required": [
        "greeting"
    ]
}
```

Actual markdown produced for this schema by `widdershins` + `shins` is the following.  The blank lines in the middle of the table seem to break the table when it's converted by `shins` into HTML.  Everything above *allOf* is correctly converted into an HTML table by the rest just appears unformatted in the HTML.  

```markdown
|Name|Type|Required|Description|
|---|---|---|---|
|» greeting|any|true|No description|

*allOf*

|»» *anonymous*|string|false|No description|

*and*

|»» *anonymous*|object|false|No description|
|»»» message1|string|true|No description|
|»»» message2|string|true|No description|
```

Expected markdown could be something like this: 

```markdown
|Name|Type|Required|Description|
|---|---|---|---|
|» greeting|any|true|No description|
|*allOf*| | | |
|»» *anonymous*|string|false|No description|
|*and*| | | |
|»» *anonymous*|object|false|No description|
|»»» message1|string|true|No description|
|»»» message2|string|true|No description|
```

**Comment by MikeRalphson** [comment]
Hi - thanks for the detailed report. Could you enable github pages on your demo repo so I can easily see the rendered html and see if it differs to what I get here?

**Comment by simondean** [comment]
@MikeRalphson I've just enabled it and here's the URL: https://simondean.github.io/widdershins-issues/one-of-in-response-schema/

**Comment by MikeRalphson** [comment]
Thanks, that's really helpful.

**Comment by JLNNN** [comment]
I just updated to v3.2.1 but it's still happening.

![bildschirmfoto 2018-04-13 um 10 33 46](https://user-images.githubusercontent.com/1099235/38725022-42b91e34-3f06-11e8-93b5-3d6e6376e35d.png)

**Comment by simondean** [comment]
@MikeRalphson sorry for the delay in getting back to you.  I've tried the new version and it's working well for me.

**Comment by simondean** [comment]
@JLNNN I was seeing a different issue.  The issue I was seeing what that only the first part of the table was rendering correctly for me (before the `oneOf` in your example).  See https://simondean.github.io/widdershins-issues/one-of-in-response-schema/ for an example.  My issue is fixed now.
