### ISSUE TITLE
Inconsistency regarding the --language_tabs option for CLI usage

### ISSUE THREAD

**Issue by anothernode** [Mermade/widdershins#106]
When using Widdershins from the CLI, the `--language_tabs` option needs to be specified *after* the input file, like this:

```
widdershins foo.yaml  --language_tabs 'python:Python' --language_tabs 'ruby:Ruby'
```

If specified before the input file it yields an error:

```
widdershins --language_tabs 'python:Python' --language_tabs 'ruby:Ruby' foo.yaml

[...]
Not enough non-option arguments: got 0, need at least 1
```

This is confusing because it's inconsistent with the usage of the other options and also with the usage help output, which instructs to specify options *before* the input file:

```
widdershins [options] {input-file|url} [[-o] output markdown]
```

**Comment by MikeRalphson** [comment]
I'm going to close this due to the existence of a (fairly standard) workaround, and inactivity. But feel free to reopen the issue if necessary.

**Comment by jwillmer** [comment]
Maybe document it?
