### ISSUE TITLE
Support multiple response examples

### ISSUE THREAD

**Issue by simondean** [Mermade/widdershins#111]
It'd be great if widdershins supported multiple response examples per operation.  

It would be handy if the description field from each response example was included in the Slate markdown generated by widdershins.

**Comment by MikeRalphson** [comment]
Hi @simondean I can't remember if you can easily test from the github repo or need an npm release, but the commit added above should allow multiple examples with descriptions.

**Comment by simondean** [comment]
Thanks for the new feature.  It's working for me with Widdershins `3.4.0`.  

Here's an example of it working: https://simondean.github.io/widdershins-issues/multiple-response-examples/
