### ISSUE TITLE
Display fixed fields on scheme

### ISSUE THREAD

**Issue by niksamokhvalov** [Mermade/widdershins#116]
I propose to show in the scheme [fixed fields](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#fixed-fields-20): `nullable`, `readOnly`, `writeOnly`.

For example:

![oas](https://user-images.githubusercontent.com/8028275/39397472-3897a9ee-4b08-11e8-8e0b-8362a969f081.png)

**Comment by MikeRalphson** [comment]
Any other votes for this? I fear it may just add a lot of `false` values to most schema tables and cause the descriptions to wrap even more than they do now.

**Comment by xeurun** [comment]
I think `nullable` most like type and is better to use `string|null` syntax. `Read/Write` can be joined to single column like `true/false` anyway this is important flags

**Comment by MikeRalphson** [comment]
Good call, and thanks everyone for the feedback.

What about using `string?` or `?string` syntax to indicate nullability? Though I do like '|null' too.

**Comment by niksamokhvalov** [comment]
We need to use a field special for this purpose: `nullable` (if you mean the syntax into specification, not the UI).

> null is not supported as a type (see nullable for an alternative solution).

See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#data-types.

**Comment by MikeRalphson** [comment]
@niksamokhvalov yes, we were talking about different UI renderings of the `nullable` property of OAS.

**Comment by MikeRalphson** [comment]
@niksamokhvalov yes, I'm liking that. Do you have the changes already done? If so, could you raise a PR?

**Comment by niksamokhvalov** [comment]
No, I haven't worked on this yet.

**Comment by MikeRalphson** [comment]
@niksamokhvalov no problem, I can whip it up pretty quickly.

**Comment by MikeRalphson** [comment]
The `|null` for nullable properties and `read-only` / `write-only` restrictions template changes are in `v3.2.6`.
