### ISSUE TITLE
headings setting does not seem to work

### ISSUE THREAD

**Issue by simondean** [Mermade/widdershins#120]
Hi.  I'm having trouble getting the `headings` setting to work.  I've created the following example: 

widdershins config: https://github.com/simondean/widdershins-issues/blob/master/headings-depth/widdershins.yaml

```yaml
resolve: true
headings: 3
```

Example HTML: https://simondean.github.io/widdershins-issues/headings-depth/#Example-API

## Actual TOC

In my `widdershins.yaml` file I've set `headings` to `3` but I'm still only getting the default of 2 levels in the left hand side TOC

```
Example API v1.0.0
    Example H2
```

## Expected TOC

```
Example API v1.0.0
    Example H2
        Example H2
```

Thanks

**Comment by MikeRalphson** [comment]
Hi @simondean - are you using Shins or Slate (or something else) to render the generated markdown?

**Comment by simondean** [comment]
Hi @MikeRalphson I’m using Shins to render the markdown

**Comment by MikeRalphson** [comment]
Hmm, having difficulty reproducing this one. When you click on `Example H2`, do you see the child `Example H3` appear in the ToC? This should also happen when you scroll down slightly. I don't think the Slate ToC (which we inherit in Shins) has support for being expanded on initial display to a particular depth.

The `--headings` option only controls how many levels of headings get *included* in the ToC.

**Comment by MikeRalphson** [comment]
Related to #121 it may be worth looking in the Javascript console to see if any JS errors are being thrown by the Slate ToC code.

**Comment by simondean** [comment]
I think I might have just found the cause. Looking at the default CSS in https://github.com/Mermade/shins/blob/master/pub/css/screen_overrides.css#L10 I can see the H3 TOC entry is set to ‘display: none’. I’ll try changing that and see if it makes the H3 entry appear

**Comment by MikeRalphson** [comment]
I believe that's just for the default unexpanded state of the nested headers, but cool if it gives you the display you need!

**Comment by simondean** [comment]
Looks like you’re right. Setting ‘display: block’ for the ‘toc-list-h3’ does make the ‘h3’s appear but they don’t collapse and expand properly. Could it be that the Slate TOC JS doesn’t support more than 2 levels of TOC? I had a look through the TOC JS but couldn’t find anything obvious that would restrict it to 2 levels of TOC

**Comment by MikeRalphson** [comment]
I've definitely tested Shins with up to 6 levels of collapsible/expandable headings. We pass in a set of selectors to the ToC JS which should pick up the extended ToC entries. This is in https://github.com/Mermade/shins/blob/7c640978296c9be9af9c6742cf433d35e798aa4d/source/javascripts/all.inc#L11

**Comment by simondean** [comment]
Rather oddly, if I stop passing ‘--inline’ to ‘skins’ then the issue seems to go away.

**Comment by MikeRalphson** [comment]
That, is a new fact! :smile: I'll take another look.

**Comment by simondean** [comment]
Disabling inlining seems to stop #121 happening as well

**Comment by simondean** [comment]
Hi @MikeRalphson.  The issue is fixed for me with Shins `v2.2.1-5`.  Thanks for the fix!

**Comment by christopher181** [comment]
Hi. I'm facing issue in getting the heading level 3(h3) to expand and collapse in the left pane. As of now im able to achieve h1 under h2.
Example: heading1
                   heading2
                   heading3
                   heading4
what i want is,
Expected: heading1
                    heading2
                        heading3.
Thanks in advance.

**Comment by christopher181** [comment]
Hi. I'm facing issue in getting the heading level 3(h3) to expand and collapse in the left pane. Is there’s any way to achieve level 3 in the left navigation bar?
Thanks in advance.
