### ISSUE TITLE
Documentation Request: Config file example

### ISSUE THREAD

**Issue by bkuhl** [Mermade/widdershins#125]
My experience with node is limited so I'm trying to piece things together.  I attempted to utilize a config file but am not seeing my custom `language_tabs`:

```
$ node node_modules/widdershins/widdershins.js --verbose --environment=widdershins.config --outfile=./slate/index.html.md ./docs/main.yaml
```

**My config**

```
var converter = require('widdershins');
var options = {
    language_tabs: [
        {'shell':'Shell'},
        {'php':'PHP'},
        {'java':'Java'},
        {'javascript':'Javascript'}
    ]
};
```

Is this the correct way to define/use a configuration?

**Comment by MikeRalphson** [comment]
Hi. The configuration file should contain a JSON object, not a fragment of Javascript. So it should look more like this:

```json
{
    "language tabs": [
        {"shell" :"Shell" },
        {"php" :"PHP" },
        {"java" :"Java" },
        {"javascript" :"Javascript" }
    ]
}
```

Happy to add an example to make this clearer.

**Comment by MikeRalphson** [comment]
Example added to `README.md`

**Comment by bkuhl** [comment]
Bingo, that did it!  Thanks!

**Comment by MikeRalphson** [comment]
Glad to hear! Thanks for raising the issue.
