### ISSUE TITLE
[Question] Referencing external files

### ISSUE THREAD

**Issue by bkuhl** [Mermade/widdershins#126]
So I just want to confirm something here cause I'm not sure if it's me or if maybe this isn't supported.

`--resolve` appears to be a flag that controls resolving http:// references.  Is this true?

I can't get `$ref` or `externalValue` to work.  I've done a lot of tweaking with relative paths but I just want to make sure this is supported and I'm not trying to get something to work that will never work.

example:

```
      responses:
        '200':
          description: '200 OK'
          content:
            application/json:
              examples:
                jsonObject:
                  externalValue: path/to/example.json
              schema:
                $ref: 'path/to/response/schema.yaml#/myShema'
```

**Comment by MikeRalphson** [comment]
Hi @bkuhl - `--resolve` covers the resolution of all **external** `$ref`s, regardless of protocol (`http:`, `https:`, `file:` or relative to the source).

If you specify the `--verbose` flag as well as `--resolve` (in fact, you can increase verbosity by repeating the `--verbose` / `-v` flag) you may see what is failing in your `$ref` resolution.

`externalValue` for `examples` is not yet supported by the underlying `swagger2openapi` tool, though there is a pending Pull Request for this functionality which will be going into the next release.

**Comment by bkuhl** [comment]
Perfect, thanks for the detailed follow up.  That's really helpful.
