### ISSUE TITLE
Apostrophe in heading breaks heading id

### ISSUE THREAD

**Issue by simondean** [Mermade/widdershins#128]
Hi. Some of my headings in the markdown of my ‘info.description’ field contain apostrophes. It causes the following error in Firefox. I’m using the ‘'’ symbol. 

’’’
Error: Syntax error, unrecognized expression: #example-heading's-text-that-includes-an-apostrophe
’’’

In Chrome I get a very similar error:

’’’
Uncaught Error: Syntax error, unrecognized expression: #example-heading's-text-that-includes-an-apostrophe
’’’

It seems to break the TOC JavaScript. The TOC doesn’t work. Nothing expands when I click on the ‘h1’s or scroll through the page. If I remove then apostrophes from the headings, then the TOC starts working again.

**Comment by MikeRalphson** [comment]
Believe this is a bug in `shins`. Should be fixed in `v2.2.1-4`. Please let me know either way.

**Comment by simondean** [comment]
Thanks. I’ll give it a try. Looking at npmjs.com the latest version I can see is ‘2.2.1-3’. Is ‘2.2.1-4’ available yet?

**Comment by MikeRalphson** [comment]
Hmm, may have omitted to actually publish. Either way, `v2.2.1-5` is there now.

**Comment by simondean** [comment]
Thanks for the fix. It’s working for me
