### ISSUE TITLE
[Question] Can you clarify for me what shallowSchemas does visually?

### ISSUE THREAD

**Issue by bkuhl** [Mermade/widdershins#132]
The below screenshot shows a current segment of our docs.  I'd like to replace the inline schema with a link to the schema.  I thought `shallowSchemas` would accomplish this, but it doesn't seem to.  So I'm not sure I understand the current explanation `Don't expand schemas past $refs` - does that mean 
it should be linking to the schema or just that it doesn't detail the rest of the schema?

![screen shot 2018-05-16 at 10 39 26 am](https://user-images.githubusercontent.com/524933/40124146-e2bfc99c-58f5-11e8-805c-7189d2bafd4e.png)

**Comment by MikeRalphson** [comment]
If you want to see the effect of `--shallowSchemas`, it's probably easiest to run the petstore example from the `defs` subdirectory with and without the option.

> Don't expand schemas past $refs

Means something like your second interpretation: "that it doesn't detail the rest of the schema". Given

```yaml
schema:
  type: object
  properties:
    foo:
      type: string
    bar:
      type: integer
    baz:
      $ref: '#/components/schemas/baz'
```

It means the definition of `baz` won't be expanded (with the additional level of chevrons etc).

It does not mean "replace the inline schema with a link to the schema". The only way to do that is to create a `$ref` in place of the inline schema and move your definition to `#/components/schemas/` (or `#/definitions/` in OpenAPI 2.0), even if it is only used once.

**Comment by Eileen0917** [comment]
hi @MikeRalphson ,

Do you know what is 'restriction' in Schema and where to assign it's value?

Thanks!

**Comment by MikeRalphson** [comment]
`Restrictions` currently shows whether a schema property is `readOnly` or `writeOnly`. You could amend or remove this column by customising the templates.

**Comment by Eileen0917** [comment]
Thanks a lot!!!
