### ISSUE TITLE
Cannot resolve external references in AsyncAPI

### ISSUE THREAD

**Issue by AdamDz** [Mermade/widdershins#133]
The `--resolve` parameter does not seem to be taken into consideration when rendering an AsyncAPI file.

**Comment by MikeRalphson** [comment]
The resolver is being extracted to a separate component, which should make this easier. Thanks for the reminder.

**Comment by MikeRalphson** [comment]
This has been **very** lightly tested, but is using the same resolver as `widdershins` has been using for openapi documents. It is included in `v3.6.0`, please chase if you have any problems with it.
