### ISSUE TITLE
After copying templates to project: TypeError: data.utils.slashes is not a function

### ISSUE THREAD

**Issue by timothymcmackin** [Mermade/widdershins#146]
**Describe the bug**
I'm getting an error on generating output MD files with customized template files. I can reproduce the issue with un-customized template files copied to my project directory and with the petstore3.json file that's in the widdershins source, which validates as an openapi 3 document. 

Do I have something at the wrong version? Are there other files that I need to copy to be able to customize templates?

* [X] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

**To Reproduce**

1. Install widdershins with `npm install -g widdershins`.
2. Clone widdershins master from github.
3. Run `widdershins widdershins/defs/petstore3.json -o petstore3.md`; output file gets generated no problem.
4. Copy templates from widdershins/templates/openapi3 to myproject/templates/ ; `cp widdershins/templates/openapi3/* myproject/templates/`.
5. Run `widdershins -u myproject/templates/ widdershins/defs/petstore3.json -o petstore3.md`.

**Expected behavior**
I expected that widdershins would generate the output MD file in the same way as before but using the copied templates so I could begin customizing the templates.

**Versions**:
- Node.js (note only LTS versions are supported): 8.1.1
- Widdershins 3.6.0

**Additional context**

Here's the error I get:

Compiling all doT templates...
Loaded def authentication.def
Loaded def authentication_none.def
Loaded def callbacks.def
Loaded def debug.def
Loaded def discovery.def
Loaded def footer.def
Loaded def links.def
Loaded def parameters.def
Loaded def responses.def
Loaded def security.def
Compiling code_go.dot to function
Compiling code_http.dot to function
Compiling code_java.dot to function
Compiling code_javascript.dot to function
Compiling code_nodejs.dot to function
Compiling code_python.dot to function
Compiling code_ruby.dot to function
Compiling code_shell.dot to function
Compiling main.dot to function
Compiling operation.dot to function
Compiling translations.dot to function
Compiling all doT templates...
Loaded def authentication.def
Loaded def authentication_none.def
Loaded def callbacks.def
Loaded def debug.def
Loaded def discovery.def
Loaded def footer.def
Loaded def links.def
Loaded def parameters.def
Loaded def responses.def
Loaded def security.def
Compiling code_go.dot to function
Compiling code_http.dot to function
Compiling code_java.dot to function
Compiling code_javascript.dot to function
Compiling code_nodejs.dot to function
Compiling code_python.dot to function
Compiling code_ruby.dot to function
Compiling code_shell.dot to function
Compiling main.dot to function
Compiling operation.dot to function
Compiling translations.dot to function
TypeError: data.utils.slashes is not a function
    at Object.eval [as operation] (eval at doT.template (/usr/local/lib/node_modules/widdershins/node_modules/dot/doT.js:133:11), <anonymous>:3:254)
    at Object.eval [as main] (eval at doT.template (/usr/local/lib/node_modules/widdershins/node_modules/dot/doT.js:133:11), <anonymous>:3:3699)
    at convertInner (/usr/local/lib/node_modules/widdershins/openapi3.js:660:30)
    at Object.convert (/usr/local/lib/node_modules/widdershins/openapi3.js:683:9)
    at Object.convert (/usr/local/lib/node_modules/widdershins/index.js:20:18)
    at doit (/usr/local/lib/node_modules/widdershins/widdershins.js:97:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/widdershins/widdershins.js:176:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by MikeRalphson** [comment]
Thanks for the report, will take a look.

**Comment by timothymcmackin** [comment]
The data.utils.slashes function that the error message is looking for is in widdershins/openapi3.js. Is there some way that I can make that file available to the transform when I'm using custom templates?

**Comment by MikeRalphson** [comment]
I think the problem stems from the fact you have two different versions of widdershins installed, from your repro steps:

1. Install widdershins with npm install -g widdershins.
2. Clone widdershins master from github.

One has `data.utils.slashes` defined and templates which depend on it (the github clone) and one doesn't (the one installed with `npm -g`). You need to copy the templates from the version you are running, not the unreleased version (or run that version instead).

**Comment by timothymcmackin** [comment]
Great, thank you!
