### ISSUE TITLE
Description fields have better support for multi-line text

### ISSUE THREAD

**Issue by pmackay** [Mermade/widdershins#147]
**Is your feature request related to a problem? Please describe.**
Could the `description` fields have better support for multi-line text (when entered with `description: |`)? [This link](https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-7-documentation/#simple-multiline-description) shows some examples. Currently widdershins I think assumes it is a single line and surrounds the text with `* ... *`.

**Describe the solution you'd like**
Insert the `description` field as-is, so all Markdown formatting in the spec is maintained and multiline descriptions render properly.

Happy to try a PR if this change is acceptable.

Great library BTW, much appreciated! :)

**Comment by MikeRalphson** [comment]
A PR would always be welcome, but it's probably worth having a look at what's already there for support of "longDescs". If I remember right, Widdershins should truncate multiline descriptions at the first cr/lf and have a following table of full descriptions, though that may only be for parameter descriptions (and you may mean elsewhere?). Sorry, on my phone at the moment so can't check.

**Comment by pmackay** [comment]
@MikeRalphson I think the initial case where I noticed this was for schema descriptions. The fix above improves how they are rendered.

**Comment by MikeRalphson** [comment]
#149 has been merged.
