### ISSUE TITLE
Summary param works on CLI but not in environment file

### ISSUE THREAD

**Issue by timothymcmackin** [Mermade/widdershins#148]
**Describe the bug**
I'm trying to use the summary parameter to show the method summary rather than the ID in the TOC, but I find that the parameter works on the CLI but not in the environment file. Does it have a different name in the environment file?

* [X] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

**To Reproduce**
1. Install widdershins 3.6.0.
2. Clone widdershins master.
3. From the widdershins folder, run `widdershins --summary defs/petstore3.json -o pet-cli.md`.
4. In pet-cli.md, note that method summaries are H2s:
```
## Add a new pet to the store
```
5. In the widdershins folder, create myEnv.json with the following contents:
```
{
  "summary": true
}
```
6. Run `widdershins --environment myEnv.json defs/petstore3.json -o pet-envfile.md`.
7. In pet-envfile.md, note that method IDs are H2s:
```
## addPet
```

**Expected behavior**
Expected the outputs to be the same WRT the H2s in the output MD.

**Versions**:
- Node.js (note only LTS versions are supported): 8.11.1

**Comment by timothymcmackin** [comment]
Looks like the option is named `tocSummary` when it's in the environment file.

**Comment by MikeRalphson** [comment]
Glad you found the solution. I think we could do better in documenting the options and their programmatic equivalents...

**Comment by timothymcmackin** [comment]
I had a look and didn't immediately see any other CLI options that have different names from the JS equivalent. Are there any more that you're aware of?

Working on a table of parameters in this branch: https://github.com/timothymcmackin/widdershins/tree/148-document-parameters

**Comment by MikeRalphson** [comment]
Thanks for the PR (#167)!
