### ISSUE TITLE
Add options to sort API methods

### ISSUE THREAD

**Issue by maaland** [Mermade/widdershins#153]
**Is your feature request related to a problem? Please describe.**
Specific methods under a certain path are not sorted by their `operationId` or anything else. So under the path `Assets` I have `getAssets`, `postAssets`, `putAssets`, `deleteAssets` etc. in that order. 

**Describe the solution you'd like**
I would like to be able to control the ordering of the methods under each path. I would be happy with simple alphanumerical ordering, but a more sophisticated ordering is desirable as well.  For the example above, I would therefore expect an ordering like `deleteAssets`, `getAssets`, `postAssets`, `putAssets` when using alphanumerical ordering. 

**Describe alternatives you've considered**
I have tried to accomplish this with the tool I am using to generate the OpenAPI files (Swagger), but to no avail. 

**Additional context**
If this is already possible with Widdershins and I have just overlooked the feature, please point me in the right direction!

**Comment by MikeRalphson** [comment]
I've not included this feature before, because I assumed the order in the OpenAPI document was the order people would want the documentation generated. In the case where the OpenAPI document is itself generated, and you are not necessarily able to affect that order, I can see that it might be a reasonable enhancement.

**Comment by MikeRalphson** [comment]
Having thought about it, I don't feel this functionality should be part of `widdershins`, if you need to pre-process your OpenAPI document to change the order of operations etc, then it should be done in a dedicated pre-processing tool.
