### ISSUE TITLE
Code samples in Markdown placed before <h> tags

### ISSUE THREAD

**Issue by stownsend2121** [Mermade/widdershins#155]
In the markdown output file, the markdown code samples within ``` (what shows up in the right pane) are located before the headings they apply to. Per [Slate](https://github.com/lord/slate/wiki/Markdown-Syntax), they should show up just after. When code samples are placed before the headings, the middle and right panes are not aligned, leaving lots of empty space in the middle pane.

Current Markdown:

``` 
```json
{
  "sessions": [
    {
      "sessionId": "1234",
      "members": [
        {
          "accountId": 1234567890,
          "onlineId": "OnlineID",
        }
      ]
    }
  ]
} ```

<h3>Responses</h3>

|Status|Meaning|Description|Schema|
|---|---|---|---| 
```

Expected: 
``` 
<h3>Responses</h3>
```json
{
  "sessions": [
    {
      "sessionId": "1234",
      "members": [
        {
          "accountId": 1234567890,
          "onlineId": "OnlineID",
        }
      ]
    }
  ]
} ```
|Status|Meaning|Description|Schema|
|---|---|---|---| 
```

An example of where they are in the OAS3 file: 

```
responses: 
   '201': 
     content: 
        application/json: 
           schema: 
              example:
```

**Comment by MikeRalphson** [comment]
Do you see this with a particular version of slate? I'm sure we've always **had** to put the examples immediately before the headings to avoid exactly the problem you're describing.

**Comment by stownsend2121** [comment]
It's version 2.3.1, but I narrowed down the issue to implementing some changes for "Deeper Nesting" in Slate. https://github.com/lord/slate/wiki/Deeper-Nesting

It looks like making the changes described in that article causes the misalignment. I'm guessing it's modifications to the following code: 

```
// the div is the tocify hidden div for placeholding stuff
& > h1,
& > h2,
& > h3,
& > div {
  clear: both;
}
```

**Comment by MikeRalphson** [comment]
As slate doesn't have that feature baked in, I can't really support it. I can only suggest having a look at https://github.com/mermade/shins instead.
