### ISSUE TITLE
Description in $ref element is not dereferenced 

### ISSUE THREAD

**Issue by maaland** [Mermade/widdershins#156]
**Describe the bug**
I have a `schema` component containing a reference to another `schema` component, which has a `description` field. When using `widdershins` to produce static documentation from the `json` file, it does not seem like referenced schema's description is being dereferenced in the parent schema referencing the schema. 

Here is a simplified version of the two schemas in question:
```
        "components": {
          "schemas": {
            "SomeDTO" : {
              "required": [ "OtherDTO" ],
              "type": "object",
              "properties": {
                "name": {
                  "type" : "string"
                }
                "otherDTO" : {
                  "$ref": "#/components/schemas/OtherDTO"
                }
              },
              "description": "Some description"
            },
            "OtherDTO": {
              "required": ["someField"],
              "type": "object",
              "properties": {
                "someField": {
                  "type": "string"
                },
                "someOtherField": {
                  "type": "string"
                }
              },
              "description": "Description of OtherDTO."
            }
          }
        }
```

The resulting `md` looks something like this
`SomeDTO`

```
### Properties

*A specification for creating a new SomeDTO*

|Name|Type|Required|Description|
|---|---|---|---|
|name|string|false|No description|
|OtherDTO|[OtherDTO](#schemaotherdto)|true|No description|
```
Above I expect `OtherDTO` to have the description "Description of OtherDTO.".

`OtherDTO`
```
### Properties

*Description of OtherDTO. *

|Name|Type|Required|Description|
|---|---|---|---|
|someField|[string]|true|No description.|
|someOtherField|[string]|false|No description|
```

* [√] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

**Versions**:
```
$ node --version
v10.4.1
```
```
$ widdershins --version
3.6.0
```

**Additional context**
This is the command I am running:

`widdershins swagger/openapi.json -x --maxDepth 5 -o index.html.md -u swagger/widdershins-templates`

Is this a bug? Or am I using widdershins incorrectly? Perhaps it's an issue with my templates? Any help is greatly appreciated.

**Comment by maaland** [comment]
@MikeRalphson I would love some feedback on this if you have the time.

**Comment by maaland** [comment]
Nudging this again @MikeRalphson

**Comment by mrtristan** [comment]
i'm also trying to figure this out. if you wind up with a solution, do please post it back here

**Comment by MikeRalphson** [comment]
Added in `v3.6.2`
