### ISSUE TITLE
External schemas not resolved

### ISSUE THREAD

**Issue by DavidBiesack** [Mermade/widdershins#159]
**Describe the bug**
When running widdershins on an openapi 2.0 input and a response schema includes a `$ref` to an external schema (i.e. `$ref: 'http://host/path/schema.json'` instead of `$ref: '#/definitions/name'` ), widdershins does not resolve that schema. We use published external JSON Schema files for schemas which are shared across multiple APIs.

* [ x] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

**To Reproduce**
1. Command-line:

```
widdershins https://gist.githubusercontent.com/DavidBiesack/567cfaf86bbcd0b210208b0d4e8f741a/raw/64eb7463afab9541a420356935f2e9083184f0c2/widdershinsExample.yaml -o /tmp/w.md
```
2. My input file: see URI in in command line above

This references an external schema which I've published as a gist, 
```
        allOf:
          - $ref: 'https://gist.githubusercontent.com/DavidBiesack/0753c16156df8d426256d85cb36c5585/raw/5a58be09cb0b83a5e7ad0fef92162a738a0a32ce/money.json'

```

3. View 'Response' schema and generated example

The generated markdown contains
```
|Name|Type|Required|Restrictions|Description|
|---|---|---|---|---|
|amount|[https://gist.githubusercontent.com/DavidBiesack/0753c16156df8d426256d85cb36c5585/raw/5a58be09cb0b83a5e7ad0fef92162a738a0a32ce/money.json](#schemahttps://gist.githubusercontent.com/davidbiesack/0753c16156df8d426256d85cb36c5585/raw/5a58be09cb0b83a5e7ad0fef92162a738a0a32ce/money.json)|false|none|A monetary amount.|
|memo|string|false|none|An optional user-assigned memo.|
```
The generated example is also wrong and does not show the fields in the external schema

```
{
  "amount": {},
  "memo": "string"
}
```
**Expected behavior**
widdershins should follow the external $ref and embed the schema found there.

**Screenshots**

**Versions**:
- Node.js (note only LTS versions are supported): v10.7.0

**Additional context**

**Comment by DavidBiesack** [comment]
The `swagger-api/swagger-parser` NPM module may be able to resolve the external $ref schemas; see https://github.com/swagger-api/swagger-parser/issues/628

**Comment by MikeRalphson** [comment]
Have you tried using the `--resolve` option as per the help/README?

**Comment by DavidBiesack** [comment]
no I missed that. That "resolves" the problem. Sorry.
