### ISSUE TITLE
Including info section using $ref fails

### ISSUE THREAD

**Issue by pmackay** [Mermade/widdershins#161]
**Describe the bug**
It is failing to parse the info section when included as a separate $ref.

**To Reproduce**

I have a doc as input to widdershins:
```
openapi: 3.0.0

info:
  $ref: info.yml
```
and an `info.yml` doc in the same folder:
```
title: Test API
version: 0.1.0
description: Test description
```

When I run this it shows:
```
node_modules/widdershins/openapi3.js:597
    data.version = (data.api.info.version.toLowerCase().startsWith('v') ? data.api.info.version : 'v'+data.api.info.version);
                                          ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at convertInner (node_modules/widdershins/openapi3.js:597:43)
    at Object.convert (node_modules/widdershins/openapi3.js:683:9)
    at Object.convert (node_modules/widdershins/index.js:20:18)
    at doit (node_modules/widdershins/widdershins.js:97:15)
    at Object.<anonymous> (node_modules/widdershins/widdershins.js:176:5)
```
* [x] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

**Expected behavior**
The external info.yml doc is included as a reference.

**Versions**:
- Node.js (note only LTS versions are supported): 8.9.1

**Comment by MikeRalphson** [comment]
I will try and fix the crash, but the `info` object cannot be replaced by a `$ref` in OpenAPI 2.0 or 3.0

**Comment by pmackay** [comment]
@MikeRalphson is it possible to include paths and schemas using:
```
paths:
  $ref: paths.yml

components:
  schemas:
    $ref: schemas.yml
```
I tried the paths include also and got a strange parsing result (18 sections numbered as `0_$ref`, `1_$ref`, etc). However if I run the file through https://github.com/BigstickCarpet/swagger-cli it reports it as valid.

It is hard to say from https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#reference-object whether this is true for only some document elements or any section.
Thanks for reply :)

**Comment by MikeRalphson** [comment]
Hi, no it is not possible to include the entire `paths` or `schemas` objects using `$ref`s, only individual `path` and `schema` objects.

`$ref` can only be used in the OAS document where the spec says it is allowed, not everywhere.

In this case, the bigstickcarpet parser is at fault.
