### ISSUE TITLE
Request to filter tags

### ISSUE THREAD

**Issue by aarengee** [Mermade/widdershins#162]
**Is your feature request related to a problem? Please describe.**
Is there a feature wherein I can specify waht tag paths to expose in the markdown generated from a swagger.json file.

**Describe the solution you'd like**
If there could be a field or option wherein I could specify which paths I want paths generated for say I have Bookings(get,post,delete) and Payments (get,post,verify) and I dont want to expose the Payment resource I would like an option to do so 

**Describe alternatives you've considered**

**Additional context**

**Comment by MikeRalphson** [comment]
It sounds like something which should be done in a pre-processing step, and not be built into Widdershins. Maybe take a look at `openapi-filter`?

**Comment by MikeRalphson** [comment]
Yes, JSON is supported, but you are misinterpreting what 'tags' relate to (in hindsight, I or the PR author should have come up with an alternative name).

`tags` relates to the actual specification extensions you want to filter on. There is no need to specify `x-internal` as it is the default.

`x-internal` is not placed within the OAS `tags` object, but is placed on the object you want to filter out.

For example:

```yaml
   "/payment/getpayment": {
      "post": {
        "x-internal": true,
        "tags": [
          ...
        ],
        "operationId": "getP",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
....
}
```

I will improve the `README` over at `openapi-filter`.
