### ISSUE TITLE
Root array response yields anonymous inline response

### ISSUE THREAD

**Issue by mrtristan** [Mermade/widdershins#169]
my swagger doc looks like
![image](https://user-images.githubusercontent.com/1546181/45323060-04d96a00-b518-11e8-87f7-863d0aba46f7.png)

which yields:
![image](https://user-images.githubusercontent.com/1546181/45323017-e70c0500-b517-11e8-821d-a08fbbb31312.png)

i'd like for that response array to be up in the top section. What needs to change for that response type to be considered non-inline? Is this functionality intended (it seems like a bug to me)?

**Comment by MikeRalphson** [comment]
For the schema to be considered non-inline, simply don't declare it inline, i.e. use a `$ref` to a definition such as:

```yaml
components:
  schemas:
    bulkOrderResponseArray:
      type: array
      items:
        $ref: '#/components/schemas/bulkOrderResponse'
```

As there is no special-casing for inline schemas using arrays, this is working as expected and not a bug.
