### ISSUE TITLE
Discrepancy in $ref behavior between OAS 2.0 and 3.0

### ISSUE THREAD

**Issue by stownsend2121** [Mermade/widdershins#170]
I cannot get external $refs to work in a simple OAS3 spec file. A Swagger 2.0 version of the same file works fine. 

* [X] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

Steps to reproduce the behavior for 2.0 file: 
1. Command-line: node widdershins petstore-20.yaml --resolve -o petstore-20.md -v
2. My input file: (please link to a gist) https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore.yaml **MODIFIED to use external $refs (e.g. "$ref: 'petstore-20-defs.yaml#/definitions/Pets')**

Output: 

![image](https://user-images.githubusercontent.com/39389284/45323059-def39b80-b4fe-11e8-935f-e2c76afd67d0.png)

![image](https://user-images.githubusercontent.com/39389284/45323086-fc286a00-b4fe-11e8-9519-0d72df6ec8ff.png)

Steps to reproduce OAS 3.0: 

1. Command-line: node widdershins petstore-30-json.json --resolve -o petstore-30.md -v
2. My input file: (please link to a gist) https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml **MODIFIED to use external $refs (e.g. "$ref: 'petstore-30-comps.yaml#/components/schemas/Pets')**

Output: 

![image](https://user-images.githubusercontent.com/39389284/45323127-195d3880-b4ff-11e8-9778-b21dd142e863.png)

![image](https://user-images.githubusercontent.com/39389284/45323266-7953df00-b4ff-11e8-808f-169fd77172b5.png)

**Expected behavior**
Expected OAS3 output to include links to schemas, similar to the Swagger 2.0 output. 

**Versions**:
3.6.0

**Comment by MikeRalphson** [comment]
Without seeing your modified input documents, I can't really help. Please could you collect them into a gist?

**Comment by stownsend2121** [comment]
main OAS file: https://gist.github.com/stownsend2121/c1a4e8526b664c24eb8e79ea594ba322
linked components file: https://gist.github.com/stownsend2121/cac890623cf97227e30c960a9a9ae1db

**Comment by andrewscea** [comment]
related issue
https://github.com/Mermade/widdershins/issues/175

**Comment by MikeRalphson** [comment]
@stownsend2121 @andrewscea please see #175

**Comment by stownsend2121** [comment]
Hi Mike, 

I referenced that issue and tried 3.6.4, but it didn't resolve my issue. Making changes to the source files to add #/components/schemas isn't feasible for us, as the engineering teams we're working with are using several separate files, each with many schema objects.

I created a gist to show what's going on. 
https://gist.github.com/stownsend2121/b58b704ccd351468c2590161f6b9f90c

Basically, two requests eventually share the same array of objects (you can start with petstore-30.yaml to see the paths for each). If you run Widdershins on petstore-30.yaml with --resolve, you'll see that for the Props-members properties the schemaType isn't being set in the manner I'd expect. It looks like the link in my original image.
