### ISSUE TITLE
csharp language_tab support?

### ISSUE THREAD

**Issue by kimwandev** [Mermade/widdershins#171]
I think it would be cool to support csharp language in generating examples under language tabs.

**Comment by matiaslarsson** [comment]
@kimwandev Have you tried the `--httpsnippet` option? 

`widdershins ./swagger.json -o ./api.md --language_tabs 'shell:CURL' 'csharp:C#' --httpsnippet`

**Comment by MikeRalphson** [comment]
I'm going to close this as there is a workaround and it is tricky to accommodate more default languages and still have everything fit on smaller screen sizes.
