### ISSUE TITLE
Cannot install the library

### ISSUE THREAD

**Issue by GeorgeGkas** [Mermade/widdershins#195]
**Describe the bug**
I cannot install the library neither with `yarn` nor with `npm`.

**To Reproduce**
1. Create a new project
2. Command-line: `yarn add widdershins` or `npm -i widdershins`

**Expected behavior**
The package should be installed.

**Screenshots**
```bash
yarn add v1.12.3
[1/4] Resolving packages...
error No valid versions found for "flatmap-stream". The package may be unpublished.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Versions**:
- Node.js (note only LTS versions are supported): all

**Comment by MikeRalphson** [comment]
See https://github.com/dominictarr/event-stream/issues/116

**Comment by GeorgeGkas** [comment]
@MikeRalphson I read the discussion but could not find a proposed solution. Did I missed anything?

**Comment by MikeRalphson** [comment]
I need to do some further reading myself...
