### ISSUE TITLE
Vertical bar symbol ( | ) in regex patterns results in malformed/dropped output

### ISSUE THREAD

**Issue by stownsend2121** [Mermade/widdershins#200]
**Describe the bug**
Using the vertical bar symbol | in a regex pattern (as an or expression) means that when it is converted into Markdown, it is treated as table formatting, which messes with the doc output. 

We convert the Markdown to HTML, which causes formatting problems. Tools like Slate simply drop the content after the | separator. 

We can escape it with '\' in markdown, but adding \ to the RegEx in OAS3 makes it a literal character and not an or operator.

Is there some other workaround?

* [X ] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

**To Reproduce**
Here's a gist: https://gist.github.com/stownsend2121/e3c8a0aac9368fe3a931a4229c2d072d

**Versions**:
Node v8.11.3 (Windows)
Widdershins 3.6.4

**Comment by MikeRalphson** [comment]
I think if we make sure `pattern` values are surrounded by back-ticks (code block) it should be ok, but perhaps escaping | is also necessary?

**Comment by MikeRalphson** [comment]
Are you using your own templates?

**Comment by stownsend2121** [comment]
Back-ticks did the trick!
