### ISSUE TITLE
safeType escape sequence breaking tables

### ISSUE THREAD

**Issue by crosoftzach** [Mermade/widdershins#206]
The += '\\|null' results in broken tables (e.g. schema field tables) in Slate.

https://github.com/Mermade/widdershins/blob/30ea3ec7fdc63f0a2ba8381f1c11379e28c05822/common.js#L358

Maybe this is actually an issue with Slate? I don't see in the Slate docs any mention of escape sequences for tables like this.

**Comment by MikeRalphson** [comment]
Probably the easiest fix if Slate doesn't support escaped table column separators, is to use an alternative vertical bar character, I think Unicode has several to choose from. If you're not averse to using a Slate alternative, [shins](https://github.com/Mermade/shins) does support GitHub style escapes for table separators and keeps everything in node.js-land.

Anyway, will be included in the next release, thanks for pointing it out.

**Comment by crosoftzach** [comment]
Really shouldn't this type of escaping be in the templates rather than in the widdershins datamodel? Even better, maybe the datamodel could include the original type/format/etc. info so templates can output however implementors choose?

**Comment by MikeRalphson** [comment]
The template itself has no way of knowing the `safeType` value needs escaping, though I suppose a helper function could be added, that's just moving Javascript from `common.js` to being **invoked** by the template, so I'm not totally sure what the advantage would be.

The original type is available in the data model as `schema.type` if I remember correctly.

**Comment by crosoftzach** [comment]
Format is missing from parameters in openapi3.js. Other fields, like nullable, default, etc. are missing from schema (schemaToArray in common.js).

**Comment by MikeRalphson** [comment]
> Format is missing from parameters in openapi3.js. Other fields, like nullable, default, etc. are missing from schema (schemaToArray in common.js).

The whole `schema` object is available, which includes all of the properties you mention (if they are defined).

**Comment by MikeRalphson** [comment]
Should be fixed in version `4.0.0`, which includes breaking changes (please see the `README.md` file).
