### ISSUE TITLE
Ability to exlude header

### ISSUE THREAD

**Issue by ryanlichwalla** [Mermade/widdershins#210]
Hey All,

I have a use case to generate the output without the header information (shown below).  Currently, I've modified the openapi3.js file to exclude it but think it might be useful for others. 

`---
title: My Rest API
language_tabs:
  - shell: Shell
  - python: Python
  - java: Java
toc_footers: []
includes: []
search: true
highlight_theme: darkula
headingLevel: 2
---`

**Comment by MikeRalphson** [comment]
Should be fixed in version `4.0.0`, which includes breaking changes (please see the `README.md` file).
