### ISSUE TITLE
`data.consumes` is not being hydrated

### ISSUE THREAD

**Issue by aeneasr** [Mermade/widdershins#216]
**Describe the bug**

In `operation.dot` the content type is set using `data.consumes`:

```
{{?data.operation.operationId=="oauthToken"}}{{=JSON.stringify(data, null, 2)}}{{?}}
{{=data.methodUpper}} {{=data.url}}{{=data.requiredQueryString}} HTTP/1.1{{? data.host}}
Host: {{=data.host}}{{?}}{{?data.consumes.length}}
Content-Type: {{=data.consumes[0]}}{{?}}{{?data.produces.length}}
Accept: {{=data.produces[0]}}{{?}}
{{?data.headerParameters.length}}{{~ data.headerParameters :p:index}}{{=p.name}}: {{=p.exampleValues.object}}
{{~}}
{{?}}
```

While `Accept` is always set (because `data.produces` is hydrated), `data.consumes` seems to be an empty array at all times. Both produces and conumes are properly set in the api definition:

```
    "/oauth2/token": {
      "post": {
        "security": [
          {
            "basic": []
          },
          {
            "oauth2": []
          }
        ],
        "description": "This endpoint is not documented here because you should never use your own implementation to perform OAuth2 flows.\nOAuth2 is a very popular protocol and a library for your programming language will exists.\n\nTo learn more about this flow please refer to the specification: https://tools.ietf.org/html/rfc6749",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "schemes": [
          "http",
          "https"
        ],
        "tags": [
          "public"
        ],
        "summary": "The OAuth 2.0 token endpoint",
        "operationId": "oauthToken",
        "responses": {
          "200": {
            "description": "oauthTokenResponse",
            "schema": {
              "$ref": "#/definitions/oauthTokenResponse"
            }
          },
          "401": {
            "description": "genericError",
            "schema": {
              "$ref": "#/definitions/genericError"
            }
          },
          "500": {
            "description": "genericError",
            "schema": {
              "$ref": "#/definitions/genericError"
            }
          }
        }
      }
    },
```

The end result should contain `Content-Type` but doesn't:

<img width="809" alt="bildschirmfoto 2019-02-13 um 17 24 39" src="https://user-images.githubusercontent.com/3372410/52726845-446b1d00-2fb4-11e9-815a-910537aca6d8.png">

* [x] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

**To Reproduce**

```
$ git clone https://github.com/ory/docs.git
$ cd docs/website
$ npm i
$ npm run swagger:generate:hydra
```

Then open `docs/hydra/sdk/api.md` and search for `opIdoauthToken` which will be lacking the `Content-Type`. I've added `{{?data.operation.operationId=="oauthToken"}}{{=JSON.stringify(data, null, 2)}}{{?}}` in `.widdershins/templates/operation.dot` to debug it and there I see that `consumes` is empty while `produces` is not:

```
  "produces": [
    "application/json",
    "application/json",
    "application/json"
  ],
  "consumes": [],
  "bodyParameter": {
    "exampleValues": {}
  },
```

The swagger definition can be found in `apis/hydra.json`.

**Expected behavior**
`data.consumes` should contain the consuming content types.

**Versions**:
- Node.js (note only LTS versions are supported): 11.4.0

**Comment by aeneasr** [comment]
I figured it out, since no parameters are given, the content-type is ignored! By adding (for example)

```
        "parameters": [
          {
            "type": "string",
            "x-go-name": "Token",
            "name": "token",
            "in": "formData",
            "required": true
          }
```

to the swagger definition above, the content type appears!

**Comment by MikeRalphson** [comment]
This is because OpenAPI 2.0 documents are internally converted to OpenAPI 3.0 where `consumes` and `produces` don't exist - those arrays on `data` are merely a convenience to make the templates easier to write.

When there is no `body` or `formData` parameters, there is nothing to attach the notion of a `consumes` media-type to, so it is omitted.

Glad you got it sorted!

**Comment by aeneasr** [comment]
It does work for responses (produces) without any body information though.

**Comment by MikeRalphson** [comment]
Because `produces` is tied to the `response` schema.

**Comment by aeneasr** [comment]
I see, thank you for the quick response!
