### ISSUE TITLE
operation data.produces contains duplicate media types

### ISSUE THREAD

**Issue by DavidBiesack** [Mermade/widdershins#220]
**Describe the bug**
in operation.dot,  data.produces array contains duplicates if an operation has multiple responses

* [x] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

**To Reproduce**
run on a valid OpenAPI. Update `operation.dot` to list produces/consumes:
```
Content-Type: {{=data.consumes}}

Accept: {{=data.produces}}
```

and you'll see duplicates

**Expected behavior**
no duplicates

**Screenshots**

**Versions**:
- Node.js 8.12

**Additional context**

I'll submit a PR - simple fix in lib/openapi3.js

**Comment by MikeRalphson** [comment]
Should be fixed in version `4.0.0`, which includes breaking changes (please see the `README.md` file).
