### ISSUE TITLE
AsyncAPI doesn't adhere `--headings` parameter

### ISSUE THREAD

**Issue by amirlanesman** [Mermade/widdershins#228]
**Describe the bug**
When using Widdershins with AsyncAPI YAML file the option `--headings` doesn't do anything.
```shell
widdershins --summary defs/asyncapi12a.yaml -o asyncapi12a.html.md --headings 2
```
still produces:
![image](https://user-images.githubusercontent.com/2202639/55416300-3464c800-5577-11e9-96cf-13e846239c7f.png)
 where you can see `Parameters` and `subscribe` are 3rd level headings.

* [X ] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x
_I have used supplied examples_

**To Reproduce**
1. Command-line:
```shell
widdershins --summary defs/asyncapi12a.yaml -o asyncapi12a.html.md --headings 2
```
2. My input file: (please link to a gist)
https://github.com/Mermade/widdershins/blob/master/defs/asyncapi12a.yaml
3. Review output headings

**Expected behavior**
`--headings` should be used in AsyncAPI similar to the way it works in OpenAPI

**Screenshots**
_above_
notice the `Parameters` and `subscribe` level 3 heading

**Versions**:
- Node.js (note only LTS versions are supported): v10.13.0
- Widdershins: current master branch

**Additional context**
The issue is with `lib/asyncapi1.js`, it can be seen in line 72:
```javascript
    header.headingLevel = 3;
```

I think it should be 
```javascript
    header.headingLevel = options.headings || 3;
```

**Comment by MikeRalphson** [comment]
Should be fixed in version `4.0.0`, which includes breaking changes (please see the `README.md` file).
