### ISSUE TITLE
CSS/JS for --html outfile output missing

### ISSUE THREAD

**Issue by kervinpierre** [Mermade/widdershins#255]
Hi,

I'm using `node widdershins --html --resolve acme-v1.yaml --outfile test.html` and that generates a HTML file.  But that file has no style or JS associated to it.

Are there templates I can apply to this file?  Otherwise, are there default CSS/JS files I can apply to this HTML?  So I don't re-invent the wheel?

-thanks

**Comment by MikeRalphson** [comment]
There are already two output modes (the default, markdown targetted at Slate or Shins) and `--respec` which provide CSS/JS themes.

`--html` on its own is definitely a "bring your own" CSS/JS option. The templates used will depend on what the input format of your yaml file is.

**Comment by kervinpierre** [comment]
Can there be a "sample" CSS/JS that we can start with?

I'd love to contribute to this effort if it helps.

Otherwise is there a contributer who's willing to work on this "basic" theme file for CSS?

Seems like there'd be a lot of reinventing the wheel otherwise.

**Comment by MikeRalphson** [comment]
That's the job of shins, it's a two step process. You should omit the `--html` option.

**Comment by kervinpierre** [comment]
Unfortunately, the shins are not an option for me.  So I'm grateful for the --html option.  The static output works perfectly.

I guess I'll merge the shin CSS manually.

But I'm very sure others will be doing the same thing.  I was trying not to duplicate effort.

**Comment by MikeRalphson** [comment]
OK, I'll bite: why can't you use shins?

**Comment by kervinpierre** [comment]
Ok, I misunderstood what shins did.  I thought they were runtime "services" that I would have to install in production.  But I see that they generate HTML static files, which is what I need.

FYI. I was willing to contribute to the project.  I clicked the sponsor button but got an error.

**Comment by MikeRalphson** [comment]
Glad we got that sorted, hope shins works out for you.

Re: the sponsor button, I guess I jumped the gun, I thought github would have rolled it out to everyone sooner.

**Comment by kervinpierre** [comment]
All works great, thanks!

Ok, well let me know how I can help.
