### ISSUE TITLE
Add details of the schema and property descriptions - with links

### ISSUE THREAD

**Issue by prakashbalaji** [Mermade/widdershins#26]
### Detailed Description

Currently the documents are generated without the details of the resource, attributes and it would be great to include the resource detail along with individual attributes details in the documentation so that the consumer of API have sufficient details. There could be a attribute which just accepts enumerated values and it is currently not possible to list them. 
Eg. To add a provider the parameter just describes type as Provider as shown below. 
<img width="744" alt="screen shot 2017-06-07 at 8 26 13 pm" src="https://user-images.githubusercontent.com/148182/26885241-bc4785aa-4bbf-11e7-8967-3142c6ace27f.png">

### Expected Behavior
Depending on complexity it would be great if we could support one of these features. A model section which lists all the resources, attributes and any description and rules like how swagger2slate generates. 
<img width="1185" alt="screen shot 2017-06-07 at 6 49 07 pm" src="https://user-images.githubusercontent.com/148182/26885357-0da76cb2-4bc0-11e7-95b6-02186c58684c.png">

Or a even better is to the way [Stripe](https://stripe.com/docs/api#customers) does by listing the resource and attributes details along with detail description.
<img width="759" alt="screen shot 2017-06-07 at 8 32 21 pm" src="https://user-images.githubusercontent.com/148182/26885520-78acbdf0-4bc0-11e7-844e-9e94cf9920b2.png">

List instead of table helps in rendering nested objects in much nicer way.

**Comment by MikeRalphson** [comment]
See also https://github.com/lbovet/docson

**Comment by MikeRalphson** [comment]
@prakashbalaji would you mind testing the latest version to see if the improvements go some way to meeting your requirements?

Let me know if you are using the npm package, and I will do a release.

**Comment by kouno** [comment]
Hi @MikeRalphson! If you create another release it would be awesome! 😄

**Comment by MikeRalphson** [comment]
@kouno Hi! Just for you, v2.1.0 has been published.

**Comment by kouno** [comment]
Just finished rebuilding our project and it looks a lot better now! Thanks for the quick reply!

**Comment by MikeRalphson** [comment]
@kouno do let me know if you spot any issues with the way request body parameters are flattened.

**Comment by MikeRalphson** [comment]
@prakashbalaji Should be fixed in v2.1.1 - please let me know if not.
