### ISSUE TITLE
Cannot pass body data request in cURL request after convert

### ISSUE THREAD

**Issue by naviat** [Mermade/widdershins#261]
**Describe the bug**

In swagger.yaml, I have the body data request in #definitions with sample data for each request. BUT I don't see it in sample code for cURL, Golang, Ruby, Java, Python section -  for Nodejs is OK.

* [x] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

**To Reproduce**
1. Command-line: `node widdershins --search true --language_tabs 'shell:cURL' 'javascript--nodejs:Node.JS' 'go:GO' 'ruby:Ruby' 'python:Python' 'java:Java' --summary swagger.yaml -o slate.md`
2. My input file: (please link to a gist): https://gist.github.com/naviat/468b00910a0c76e917a82461f625fc34
4. See error: Don't see any data sample for cURL, Golang, Ruby, Java, Python section.

**Expected behavior**
 
Get the body data in cURL, Golang, Ruby, Java, Python  request

**Screenshots**

cURL:

![image](https://user-images.githubusercontent.com/13325589/65867574-dc314600-e3a0-11e9-8214-fa14d9433246.png)

Nodejs:
![image](https://user-images.githubusercontent.com/13325589/65867605-ece1bc00-e3a0-11e9-8adb-68c9cb90b757.png)

**Versions**:
- Node.js (note only LTS versions are supported):  v8.16.1

**Additional context**

**Comment by naviat** [comment]
Move to use another `httpsnippet key` (follow Kong template) for Nodejs by change command parameter `javascript--nodejs:Node.JS` to `node:Node.JS`.

Close this after clear. Thanks

**Comment by dylanirlbeck** [comment]
@naviat I'm having the same issue with not being able to generate code snippets. Can you elaborate on what your fix was? I'm a little confused by your solution here:

> Move to use another httpsnippet key (follow Kong template) for Nodejs by change command parameter javascript--nodejs:Node.JS to node:Node.JS.

**Comment by dylanirlbeck** [comment]
As a follow-up, I just found my problem. In my command line I needed to include the `--httpsnippet` flag.
