### ISSUE TITLE
user templates are not working

### ISSUE THREAD

**Issue by TA2k** [Mermade/widdershins#262]
**Describe the bug**
A clear and concise description of what the bug is. Reports containing a full reproduction recipe (command-line and input file gist) will get a **much** faster response.

* [x] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

**To Reproduce**
Install widdershins from github master localy
copy templates from node_modules in folder user_templates
use options.json 
{
    "user_templates": "./user_templates/"
  }
as environment
rename in user_templates/openapi3/parameters.def for example the "In" in the parameter table
use local whiddershins to convert json
    ../../node_modules/.bin/widdershins --environment options.json $f -o $f.md
 
This change is not effecting the output. When I change it in the templates of the installed widdershins than it will change in the output markdown.

Path is ok and markdown is generates without errors.

**Comment by MikeRalphson** [comment]
Please try copying the openapi3 templates directly into your user_templates directory, and not into a subdirectory.

**Comment by TA2k** [comment]
I thought I tested this. But this is now working. Sorry.
