### ISSUE TITLE
New release on npm

### ISSUE THREAD

**Issue by TA2k** [Mermade/widdershins#265]
**Describe the bug**
Can you please publish a new version on npm. We cannot use the github link to the master branch, we have to rely on the npm versions but in this 10 month old 3.6.7 there are feature missing like omitHeader we need because this header is breaking our rendering.

**Comment by chanjoongkim** [comment]
+1 on this issue, we would also like to utilize the `omitHeader` feature from the npm package.

**Comment by galvo** [comment]
+1 on this

**Comment by Hydragyrum** [comment]
+1, master branch fixes a few bugs

**Comment by MikeRalphson** [comment]
Unfortuately, `master` also seems to contain a few bugs which may be regressions. Apologies for the delay and frustration, I'll try and devote some time to widdershins soon.

**Comment by MikeRalphson** [comment]
Version `4.0.0` has been released, which includes breaking changes (please see the `README.md` file).
