### ISSUE TITLE
Getting TypeError: Cannot read property 'schema' of undefined

### ISSUE THREAD

**Issue by chandrakalatue** [Mermade/widdershins#270]
**Describe the bug**
Trying to convert the OpenAPI3.0.1 file to MarkDown file

* [x] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

**To Reproduce**
1. Installed Widdershins
2. Navigate to the folder where widdershins is installed
3. Open Command-line and log in as root user
4. Run the command - node widdershins --search false --language_tabs 'ruby:Ruby' 'python:Python' 'json: JSON' --summary /home/tuebora/Desktop/openapi.json -o openapi.md
4. See error - TypeError: Cannot read property 'schema' of undefined
    at Object.eval [as operation] (eval at <anonymous> (/usr/lib/node_modules/widdershins/node_modules/dot/doT.js:133:11), <anonymous>:3:4252)
    at Object.eval (eval at <anonymous> (/usr/lib/node_modules/widdershins/node_modules/dot/doT.js:133:11), <anonymous>:3:3595)
    at convertInner (/usr/lib/node_modules/widdershins/openapi3.js:663:30)
    at Object.convert (/usr/lib/node_modules/widdershins/openapi3.js:686:9)
    at Object.convert (/usr/lib/node_modules/widdershins/index.js:20:18)
    at doit (/usr/lib/node_modules/widdershins/widdershins.js:99:15)
    at Object.<anonymous> (/usr/lib/node_modules/widdershins/widdershins.js:180:5)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)

**Expected behavior**
The file must get converted and saved as openapi.md

**Screenshots**
Error and file used for conversion are attached
**Versions**:
- Node.js (note only LTS versions are supported): v6.17.1
![Error](https://user-images.githubusercontent.com/53813388/68854402-fd0beb80-0701-11ea-82b9-21c2b18e2999.png)
[openapi.zip](https://github.com/Mermade/widdershins/files/3846274/openapi.zip)

**Comment by chandrakalatue** [comment]
I have installed Widdershins using npm install -g widdershins command. 

How to get this change updated in our deployment?

**Comment by chandrakalatue** [comment]
after taking the fix now I am getting the error - Cannot read property 'section' of undefined

**Comment by MikeRalphson** [comment]
With the same input file?

**Comment by chandrakalatue** [comment]
Yes with the same input file.

**Comment by chandrakalatue** [comment]
Any update on the error reported?

**Comment by chandrakalatue** [comment]
Please let me know the update on this. Will this be addressed Or the JSON format has some issue?

**Comment by MikeRalphson** [comment]
With the fix made as above and your submitted input file, I don't see such an error. Can you double check the `{{?}}` template change has been made in the right place in your copy?

**Comment by chandrakalatue** [comment]
I have installed Widdershins using npm install -g widdershins command.

How to get this change updated in our deployment?

Do I need to build or download the project zip and replace the files in the openapi3 folder?

**Comment by chandrakalatue** [comment]
I downloaded the project as ZIP and replaced all the files in open Api3 folder. Now I am getting the following error for the same input file

[root@slate widdershins]# node widdershins --search true --language_tabs 'ruby:Ruby' 'python:Python' 'json: JSON' --summary /home/tuebora/Desktop/openapi.json -o openapi.md
Compiling all doT templates...
Loaded def authentication.def
Loaded def authentication_none.def
Loaded def callbacks.def
Loaded def debug.def
Loaded def discovery.def
Loaded def footer.def
Loaded def links.def
Loaded def parameters.def
Loaded def responses.def
Loaded def security.def
Compiling code_go.dot to function
Compiling code_http.dot to function
Compiling code_java.dot to function
Compiling code_javascript.dot to function
Compiling code_jquery.dot to function
Compiling code_nodejs.dot to function
Compiling code_php.dot to function
Compiling code_python.dot to function
Compiling code_ruby.dot to function
Compiling code_shell.dot to function
Compiling main.dot to function
Compiling operation.dot to function
Compiling translations.dot to function
undefined:3
var out=''; data.translations.defaultTag = 'Default'; data.translations.response = 'Response'; data.translations.responseDefault = 'Default'; data.translations.responseUnknown = 'Unknown'; data.translations.schemaInline = 'Inline'; data.translations.schemaNone = 'None'; data.translations.externalDocs = 'External documentation'; data.translations.secDefNone = 'None'; data.translations.secDefScopes = 'Scopes'; data.translations.anonymous = 'anonymous'; data.translations.continued = 'continued'; data.translations.indent = '»'; data.translations.readOnly = 'read-only'; data.translations.writeOnly = 'write-only'; data.tags = {}; data.tags.section = data.options.respec ? '<section>' : ''; data.tags.endSection = data.options.respec ? '</section>' : ''; out+='\n';return out;
                                                                                                                                                                                                                                       

TypeError: Cannot read property 'respec' of undefined
    at Object.eval [as translations] (eval at <anonymous> (/usr/lib/node_modules/widdershins/node_modules/dot/doT.js:133:11), <anonymous>:3:665)
    at convertInner (/usr/lib/node_modules/widdershins/openapi3.js:595:15)
    at Object.convert (/usr/lib/node_modules/widdershins/openapi3.js:686:9)
    at Object.convert (/usr/lib/node_modules/widdershins/index.js:20:18)
    at doit (/usr/lib/node_modules/widdershins/widdershins.js:99:15)
    at Object.<anonymous> (/usr/lib/node_modules/widdershins/widdershins.js:180:5)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
[root@slate widdershins]#

**Comment by MikeRalphson** [comment]
Using templates from the unreleased master version with an older release is unsupported, sorry.

You can try to modify your `openapi3.js` file to move the declaration of `data.options` before the templates are evaluated...

**Comment by chandrakalatue** [comment]
when is the next release with this bug being fixed? How will I come to know about future releases?

Can you give me the steps that I need to perform - to "modify your openapi3.js file to move the declaration of data.options before the templates are evaluated..."

Sorry, I am asking for steps because I am not a developer (does not have experience in coding). I am into the documentation of API and have only a basic understanding of the tool.

**Comment by MikeRalphson** [comment]
Sorry, I should have closed this when `v4.0.0` was released. The best way to subscribe to new releases is to "Watch" the repository, and select "Releases Only".
