### ISSUE TITLE
Multiple operation tags are ignored

### ISSUE THREAD

**Issue by maciejzgadzaj** [Mermade/widdershins#296]
**Describe the bug**
Currently, when an operation is assigned to multiple tags, widdershins uses only the first tag and ignores the rest. 

This PR fixes this issue: https://github.com/Mermade/widdershins/pull/295

* [x] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

**To Reproduce**
Use example file with 1 operation with 2 tags: https://gist.github.com/maciejzgadzaj/4e50be5654cb7ff413ec20ffe47e5e77

Convert it to markdown with current version - the operation will be added to first tag only (here: "cats").

**Expected behavior**
When converting to markdown, the operation should be added to all defined tags (here: "cats" and "dogs").

**Comment by MikeRalphson** [comment]
As discussed on the PR, this is not a bug, this is the intended behaviour. It might be worth adding an **option** to create links back to the operation description where multiple tags are used, but simply repeating the operation under each tag is not desired behaviour.
