### ISSUE TITLE
Encoding of query params in code examples is wrong

### ISSUE THREAD

**Issue by accnops** [Mermade/widdershins#298]
**Describe the bug**

* [x] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

URL query params are wrongly encoded in the code examples. Activating httpsnippet does not solve this issue.

The code example shows: `http://10.0.0.254:4000/analytics/heatmap?time=1561368466879%2C1571368466879&bucket%252Dsize=500`

It should be: `http://10.0.0.254:4000/analytics/heatmap?time=1561368466879,1571368466879&bucket-size=500`
OR
`http://10.0.0.254:4000/analytics/heatmap?time=1561368466879%2C1571368466879&bucket%2Dsize=500`
(notice the difference, bucket%252Dsize vs. bucket%2Dsize)

**To Reproduce**
1. Command-line: `widdershins analytics.yml -o output.md`
2. My input file: https://gist.github.com/accnops/cbaf661ff1678104f4ee9727c9cf8b42
3. Scroll down to line 40 in `output.md`
4. See wrongly encoded query params

**Expected behavior**
The code example shows: `http://10.0.0.254:4000/analytics/heatmap?time=1561368466879%2C1571368466879&bucket%2Dsize=500`

It should be: `http://10.0.0.254:4000/analytics/heatmap?time=1561368466879,1571368466879&bucket-size=500`
OR
`http://10.0.0.254:4000/analytics/heatmap?time=1561368466879%2C1571368466879&bucket%2Dsize=500`
(notice the difference, bucket%252Dsize vs. bucket%2Dsize)

**Comment by accnops** [comment]
Widdershins seems to be only part of the problem. The query param name is first passed through the function `stupidity` (yes, it's really called that way). There it turns `bucket-size` into `bucket%2Dsize`. Which is fine.

It then gets passed to the library URI.js. There, it gets encoded a second time, turning `bucket%2Dsize` into `bucket%252Dsize`, essentially encoding it two times, which is wrong. I did a short experiment with URL.js, trying to pass `bucket-size`. It does not accept hyphens and errors with `Error: Invalid Variable Name`. The library also does not have an option for disabling encoding.

Thoughts about how to handle this properly?

**Comment by MikeRalphson** [comment]
As I remember, the `stupidity` function is there to force OAS-allowed but [RFC6570](https://tools.ietf.org/html/rfc6570) banned template parameter names (like ones containing hyphens) through `uri.js` functions.

I thought there was a reverse function to undo double-encoding but it's not jumping out at me. It looks like it needs adding or extending to cope with more cases, yours included.

**Comment by accnops** [comment]
Ok understood, thank you.

I sent a pull request that also applies this fix to uriExample and requiredUriExample. This resolves my issue.
