### ISSUE TITLE
user_templates option one level up

### ISSUE THREAD

**Issue by accnops** [Mermade/widdershins#299]
**Is your feature request related to a problem? Please describe.**
I have a mixed documentation project: OpenAPI + AsyncAPI. I can't define the `user_templates` option for both, so I'm forced to build separately.

**Describe the solution you'd like**
It would be nice if I would be able to just pass the path to my templates with following structure:

- templates/
    - openapi3/
        - main.dot
        - ...
    - asyncapi1/
        - main.dot
        - ...

Now I can only pass the option on the level of `templates/openapi3/`. I can't set the option to `templates/`. It would be great if I could do that.

I understand this breaks the API, but it makes more sense in my opinion.

**Comment by MikeRalphson** [comment]
As Widdershins only takes one input file at a time, how would this avoid you having to build your OpenAPI and AsyncAPI markdowns separately?

**Comment by accnops** [comment]
Solid point! I forgot we have a wrapping library around it that produces multiple pages.

Could in any case be considered to be a more elegant solution. What do you think?
