### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by MikeRalphson** [Mermade/widdershins#3]
Anything considered - for example a clock face with arrows going anti-clockwise with {A} in the centre. 

Create in a docs/ directory.

**Comment by LatGeek** [comment]
What kind of logo do you need, ASCII? Bitmap? What would the size of it be?

**Comment by MikeRalphson** [comment]
@latgeek the best option would be a vector format, such as SVG, but a bitmap would be fine, around 640x480 to go on the README.md. Thanks!

**Comment by LatGeek** [comment]
I am rusty as hell with Inkscape, but I came up with these two. Either of 'em up to snuff? Anything you'd want in them? 
![2016-10-16_06-31-23](https://cloud.githubusercontent.com/assets/22866186/19416677/761f753e-936d-11e6-9971-0e77c2d72764.png)
![2016-10-16_06-53-48](https://cloud.githubusercontent.com/assets/22866186/19416678/761fec26-936d-11e6-9f59-8c3945d3d3a4.png)

**Comment by MikeRalphson** [comment]
@LatGeek fab, only problem is choosing between the two! I think the second one is more visually striking, so a pull-request to add that would be great. Thanks again.
