### ISSUE TITLE
Please document how YAML file structure results in markdown structure?

### ISSUE THREAD

**Issue by Serban-PLT** [Mermade/widdershins#318]
**Is your feature request related to a problem? Please describe.**
Hi! I'm trying to use Widdershins to convert an OpenAPI standard YAML file to Markdown for Slate. The required OpenAPI parameter `paths` results in a single section named "Default", which contains every verb of every endpoint, at the same level, and after that `schemas` get put into the Schemas section. We need to add more structure to our TOC and I have been unable to find anything in the OpenAPI standard or the documentation here about how to get multiple top-level sectionis. Please see example here (taken from the `Widdershins in the wild` section) 

https://speckleworks.github.io/SpeckleSpecs/#authentication

Example screenshot:

![image](https://user-images.githubusercontent.com/61792079/78128124-4ccb2500-740d-11ea-8775-4eb39c10141b.png)

**Describe the solution you'd like**
Could you please add documentation or a reference on what YAML file structure the library expects and how changing that would impact the outputted Markdown structure?

**Describe alternatives you've considered**
Attempts at reverse engineering source code or understanding the OpenAPI standard but I have found no YAML file matching the kind of example in the link, with multiple top-level expandable sections.

**Comment by MikeRalphson** [comment]
You're right this could be better documented than just relying on the examples (though the `petstore` one should provide a hint).

The top level `tags` object in OpenAPI provides the entries for the table of contents. Each operation should link up to a `tag`, and providing a concise `operationId` on each operation provides the second level of ToC entries.

I'll add this to the docs before closing this issue, but let me know if you hit any other problems.

**Comment by Serban-PLT** [comment]
@MikeRalphson thank you so much for clarifying, that was exactly what we needed!

**Comment by MikeRalphson** [comment]
Documentation now up at https://mermade.github.io/widdershins/MarkdownTOCStructure.html

Thanks again for flagging this up.

**Comment by Serban-PLT** [comment]
@MikeRalphson Thank you for adding that and letting me know!
