### ISSUE TITLE
Mistake in openapi3/schema_properties.dot?

### ISSUE THREAD

**Issue by cyberbliss** [Mermade/widdershins#34]
Hi
In the Properties section of schema_properties.dot the table doesn't get generated correctly 'cos the 2nd row has too many columns (5 instead of 4):

```
Name|Type|Required|Description
---|---|---|---|---|
```
Easy enough to override this template with a user one that corrects this, but thought you'd like to know for your next release.

cheers.... Steve

**Comment by MikeRalphson** [comment]
Many thanks for spotting this. Will just let CI run then will cut a new release.

**Comment by MikeRalphson** [comment]
Fixed in v2.1.2 - thanks again.
