### ISSUE TITLE
user_templates on CLI, both env and parameter not rendering as template

### ISSUE THREAD

**Issue by cesarjhony** [Mermade/widdershins#345]
user_templates on CLI, both env and parameter not rendering as template

**To Reproduce**
1. Command-line: `npx widdershins ../web/api.json -o ../web/api.md --user_templates template`
2. Copy "responses.def" to "template" folder, then remove "Restrictions" and save
3. My input file: https://app.swaggerhub.com/apiproxy/schema/file/apis/cesarjhony/pione/1.0.0?format=json
4. The command line show
```
Compiling all doT templates...
Loaded def authentication.def
Loaded def authentication_none.def
Loaded def callbacks.def
Loaded def debug.def
Loaded def discovery.def
Loaded def footer.def
Loaded def links.def
Loaded def parameters.def
Loaded def responses.def
Loaded def security.def
Compiling code_csharp.dot to function
Compiling code_go.dot to function
Compiling code_http.dot to function
Compiling code_java.dot to function
Compiling code_javascript.dot to function
Compiling code_jquery.dot to function
Compiling code_nodejs.dot to function
Compiling code_php.dot to function
Compiling code_python.dot to function
Compiling code_ruby.dot to function
Compiling code_shell.dot to function
Compiling main.dot to function
Compiling operation.dot to function
Compiling translations.dot to function
Compiling all doT templates...
Loaded def responses.def
```
5. Then the api.md file is iqual than without custom template

**Expected behavior**
Print md file without 'Restrictions'. Note: in git clone method and changing the template/openapi3/responses.def was work rigth

**Screenshots**

**Versions**:
- Node.js (note only LTS versions are supported):  10

**Additional context**
Windows 10 64bit

**Comment by MikeRalphson** [comment]
See this section of the `README`:

> The templates include `.dot` templates and `.def` partials. To override a `.dot` template, you must copy it and the child `.def` partials that the template references. Similarly, to override a `.def` partial, you must also copy the parent `.dot` template. For OpenAPI 3, the primary template is `main.dot` and its main child partials are `parameters.def`, `responses.def`, and `callbacks.def`.
This means that it is usually easiest to copy all `.dot` and `.def` files to your user templates directory so you don't skip a template or partial.

**Comment by cesarjhony** [comment]
Thank you and I apologize for my little attention, worked just if all entire .dot and .def files are in my custom template folder.
Good Morning. :D

**Comment by MikeRalphson** [comment]
Glad it's working, have a great day.
