### ISSUE TITLE
Bug with how multiple references to the same schema object are processed

### ISSUE THREAD

**Issue by cyberbliss** [Mermade/widdershins#35]
Hi

I've noticed that if, in the Swagger spec definitions section, I define an object which defines the same $ref for more than one property then only the first of these properties gets rendered to markdown, e.g.
```
definitions:
  NewThing:
    type: object
    required:
      - origin
      - destination
    properties:
      origin:
        $ref: '#/definitions/LatLong'
      destination:
        $ref: '#/definitions/LatLong'
```
Only origin appears correctly in the markdown and there is no trace of destination (LatLong is defined further down the swagger file).

Regards... Steve

**Comment by cyberbliss** [comment]
Further to my previous comment it looks like the issue is within the extract function in common.js; something to do with the `already` variable being set to true when the LatLong object is processed for the 2nd time. My JS is not good enough to figure out the specific intent of this code though.

**Comment by MikeRalphson** [comment]
Yes, that makes sense, thanks.

**Comment by MikeRalphson** [comment]
@cyberbliss I've made some changes to the way objects are dereferenced prior to the `extract` function flattening the definition. Can you let me know if you need a new npm release in order to test the fix?

**Comment by cyberbliss** [comment]
@MikeRalphson many thanks for the fix. I've just tested it and it looks fine - both origin and destination are present in the markdown in the way that I would expect.

**Comment by MikeRalphson** [comment]
Thanks for confirming, and for reporting the bug in the first place, it's much appreciated.
