### ISSUE TITLE
Support YAML merge key '<<' when parsing OpenAPI YAML specs 

### ISSUE THREAD

**Issue by alfrunes** [Mermade/widdershins#407]
**Is your feature request related to a problem? Please describe.**
It is very handy to use OpenAPI [Specification Extensions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#specification-extensions) to define a set of template YAML anchors (e.g. default error responses) which can be reused across API endpoints instead of repeating yourself.The problem is that the [yaml](https://www.npmjs.com/package/yaml) package does not enable  [YAML merge keys](https://yaml.org/type/merge.html) by default.

**Describe the solution you'd like**
It's pretty straight forward: enable the [merge option](https://eemeli.org/yaml/#options) to true when parsing YAML files. I can create a PR if you like.

**Describe alternatives you've considered**
*n/a*

**Additional context**
Example OpenAPI snippet:
```yaml
openapi: 3.0.3
# ...
x-default-responses: &default-responses
  400:
    $ref: '#/components/responses/BadRequest'
  401:
    $ref: '#/components/responses/Unauthorized'
  415:
    $ref: '#/components/responses/UnsupportedMediaType'
  500:
    $ref: '#/components/responses/InternalServerError'
# ...
paths:
  /just/do/it:
    post:
      # ...
      responses:
        <<: *default-responses
        200:
          description: OK
        418:
          description: I'm a teapot!
# ...
components:
  # ...
```

**Comment by MikeRalphson** [comment]
The problem is that YAML merge keys are a feature of YAML 1.1 which was dropped in YAML 1.2 - and OpenAPI v3 mandates the use of YAML 1.2. Using YAML merge keys in OAS v3 makes your definition non-portable.

We could enable YAML merge keys for (internally converted) OAS 2.0 documents, but this might be more confusing.

One solution is to rewrite your document in YAML 1.2 or JSON before passing it to Widdershins.

**Comment by alfrunes** [comment]
I was not aware that this feature was dropped in YAML 1.2, and I completely agree.
Sorry about the confusion.

**Comment by MikeRalphson** [comment]
No problem. You could also try adding a `%YAML 1.1` directive at the top of your file to force YAML 1.1 parsing.
