### ISSUE TITLE
Chevron symbols appearing on converted markdown

### ISSUE THREAD

**Issue by JManyama** [Mermade/widdershins#411]
**Describe the bug**
When running Widdershins, I noticed that the Schema tables display a series of Chevron symbols right before the each line of text on the table. It shows up like this:

Ex. Widdershins Budget.swagger.json -o budget.swagger.json.md

|» BudgetCategory|[BudgetCategory](#schemabudgetcategory)|false|none|none|
|»» description|string|false|none|none|
|»» expenseTypes|[[ExpenseType](#schemaexpensetype)]|true|none|The list of expense types that this budget category matches.|
|»»» ExpenseType|[ExpenseType](#schemaexpensetype)|false|none|none|
|»»»» expenseTypeCode|string|false|none|The alphanumeric code that describes an expense type. Ex: TRAVEL, AC_CATER Any string may be used, but only expense type codes returned by GET /budgetCategory/expenseType will behave properly in the Concur UI.|
|»»»» featureTypeCode|string|false|none|The type of feature that this expense type applies to, Purchase Request, Payment Request (Invoice), Expense or Travel Authorization|
|»»»» id|string|false|none|The unique idenifier for the expense type|
|»»»» name|string|true|none|none|
|»»»» syncGuid|string|false|none|The unique idenifier for the expense type|
|»» id|string|false|none|The unique identifier for the budget category.|
|»» name|string|true|none|The name of this budget category.|
|»» statusType|string|false|none|The status of this budget category--only open and removed are meaningful for budget category.|
|»» syncGuid|string|false|none|The unique identifier for the budget category.|

Screenshot:

![image](https://user-images.githubusercontent.com/74265784/102801992-d8555f00-436a-11eb-8711-2807e39a5cd2.png)

Is there a way I can prevent these symbols from showing up inside the table?

Thanks.

**Comment by MikeRalphson** [comment]
The chevrons indicate the depth of nesting of properties within your schemas.

If you wish to disable this, you can override the default templates and in `translations.dot` you can amend this line:

```dot
data.translations.indent = '»';
```

Setting it to the empty string will disable indenting of properties.

**Comment by JManyama** [comment]
I updated the translations.dot file and removed the chevron, however after running Widdershins again, the same formatting is appearing

[cid:image003.jpg@01D6D796.B77172A0]

I suspect I must be missing some step here. Thanks again for your help.
