### ISSUE TITLE
Is it possible to  inject custom elements?

### ISSUE THREAD

**Issue by madhawa-se** [Mermade/widdershins#416]
I want to add a link end of each controller .But I don't want to add it manually to auto generate md file. Is it possible to inject custom markup so I can insert a link ?

**Comment by MikeRalphson** [comment]
The easiest way would be to copy the templates and use the `--user_templates` option to point to your new directory. The amended template could pull the link value from a specification extension.

**Comment by madhawa-se** [comment]
> The easiest way would be to copy the templates and use the `--user_templates` option to point to your new directory. The amended template could pull the link value from a specification extension.

thank you. I will try that out.
