### ISSUE TITLE
requestBody in code samples incorrectly uses schema

### ISSUE THREAD

**Issue by shalvah** [Mermade/widdershins#417]
When using a schema object (via `$ref`) to describe the requestBody, the generated request body in the code samples merely copies the schema. Eg:

Operation:

```
    "/do-stuff": {
      "post": {
        "requestBody": {
          "description": "Things.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TheRequest"
              }
          }
        },
```

Components:

```
"TheRequest": {
        "properties": {
          "orderAmount": {
            "type": "number"
          },
          "orderCurrency": {
            "type": "string",
            "example": "NGN"
          },
          "cardNumber": {
            "type": "string",
            "example": 4242424242424242
          },
        },
        "type": "object"
}
```

Result:

![image](https://user-images.githubusercontent.com/14361073/105180871-65870180-5b2b-11eb-92b5-f46a87e4ffa3.png)

* [x] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

Sorry, I can't share the full spec as it's a private project.

**Versions**:
- Node.js 14.8
- Widdershins 4.0.1

I'm currently looking into somehow shimming the `common.getSampleInner` method to work around this. It returns the schema rather than the example only. Oh, and this happens for headers too.

**Comment by shalvah** [comment]
Oh wow. Just discovered `options.sample` does this, but this option isn't listed in the table of options in the README. An oversight?

With `options.sample` , I get this:

![image](https://user-images.githubusercontent.com/14361073/105186538-1db7a880-5b32-11eb-8d4e-b07f54dd05a3.png)

Would be good to list it in the table. I also think that `true` should be the default. I don't see a scenario where anyone wants the schemas in their code samples.

**Comment by MikeRalphson** [comment]
See #329 / #379 - `options.sample` will default to `true` in API mode in the next release. The README was also updated.

**Comment by shalvah** [comment]
Ah, cool. Thanks.
