### ISSUE TITLE
openapi3; finish support for callbacks

### ISSUE THREAD

**Issue by MikeRalphson** [Mermade/widdershins#44]
* See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#callbackObject

The work to extract `processOperation()` has been done. Just required is to make the `pathItem` more like a `resource` used elsewhere, and to output an enclosing `<div></div>` with a configurable `class` name so renderers (like shins) can put a box or 'well' around the callback to distinguish it from the containing operation.

**Comment by glock18** [comment]
Hi there!

Mike, looking at master branch sources right now, and I can't see what's actually done for callbacks. I see a bunch of TODO's mentioning callbacks, some with question marks. 

I've just started looking into the source, so any guidance on how I could finish your work would be nice! I only have limited time for this issue unfortunately, I'll have to settle on some hacky solution if my attempts will not lead to a relatively fast solution :) Right now I'm using additional path items per each callback, with a specific tag, which doesn't seem to be totally great to be honest

Thanks!

**Comment by MikeRalphson** [comment]
As above, all that's been done so far is refactoring out `processOperation()` in readiness. A `callback` object in OAS3 is just a wrapper for `pathItem` objects, and they are (mainly) just collections of `operations`. For each callback in an operation (or $ref'd by one) we should output a surrounding `<div>` with a configurable class and call `processOperation` for each operation within.

The 

```javascript
 data.resource = resource; // TODO for callbacks?
```

comment refers to the operation context having a reference to a parent `resource`. `resources` in widdershins terms are just `paths` grouped by `tags`. It should be possible to set this to the `callback` object and adjust the documentation to match.

> Right now I'm using additional path items per each callback, with a specific tag

Not sure I totally understand this... Care to expand on your approach? Are you mutating the structure of the document by creating new pathItems for each callback? If so, that sounds too limiting, as an operation within a `callback` can have its own `callbacks` etc. Hence the `<div>` to be able to show the nesting visually.

**Comment by glock18** [comment]
> Not sure I totally understand this... Care to expand on your approach? Are you mutating the structure of the document by creating new pathItems for each callback? If so, that sounds too limiting, as an operation within a callback can have its own callbacks etc. Hence the <div> to be able to show the nesting visually.

There is that limit you mention, the case you describe though seems rather unlikely to me...

I'll see what I can do with callbacks support

**Comment by MikeRalphson** [comment]
In progress on the v3.0 branch, by simply calling the new `operation.dot` template again within a nested `<div>`.

**Comment by MikeRalphson** [comment]
Included in v3.0.0 - the styling of the nested `<div>` can be done in `shins` with the override CSS.
