### ISSUE TITLE
Details about how to customize language tabs in command line

### ISSUE THREAD

**Issue by dark94da** [Mermade/widdershins#47]
Hi Mike,
 I just read all the issues and the readme.md in project and tried for several times to get a customize language tabs using command line. I tried to use -e option like _widdershins -e config.json test.json -o test.md_ . 
And in config json, I used json format option content like `options.language_tabs = [{ 'http': 'HTTP' }, { 'javascript': 'JavaScript' }, { 'javascript--nodejs': 'Node.JS' }, { 'python': 'Python' }, { 'ruby': 'Ruby' }];` or `"options.language_tabs" = [
		{ "http": "HTTP" }, 
		{ "javascript": "JavaScript" }, 
		{ "javascript--nodejs": "Node.JS" }, 
		{ "python": "Python" }, 
		{ "ruby": "Ruby" }];`
However, it just didn't work. Thus I wandering how should I write the config file to achieve this goal. If you can give a more specific sample for this, that would be very helpful.
Again, thanks for your hard-working on this project! It really helps a lot.

**Comment by MikeRalphson** [comment]
HI @dark94da - sorry for the confusion, and for the extra reading you've had to do!

Your command-line is fine, but the `config.json` should contain a `json` object, not `javascript` code, representing the `options` object, so it should look more like:

```json
{
  "language_tabs":  [{ "http": "HTTP" }, { "javascript": "JavaScript" }, 
    { "javascript--nodejs": "Node.JS" }, { "python": "Python" }, 
    { "ruby": "Ruby" }]
}
```
I'll update the README to make this clearer - or feel free to raise a PR (especially if you're registered for Hacktoberfest!).

Thanks for the encouraging words - means a lot!

**Comment by dark94da** [comment]
Yes, I try your code and It works! Thanks, Mike!

BTW, I just googled "Hacktoberfest" and registered it. I will go through the issues and see if I can do some help :)

**Comment by MikeRalphson** [comment]
Awesome. Many thanks again for confirming it worked. Happy hacking!
