### ISSUE TITLE
Is it possible to fetch json file from server instead of disk?

### ISSUE THREAD

**Issue by mrshawn191** [Mermade/widdershins#48]
Hi, 

Is it possible to fetch json file from server instead of disk?

I would like to run something like 

node widdershins http://localhost:8080/test/v2/api-docs -o index.html.md markdown

**Comment by MikeRalphson** [comment]
Could be done easily using the `node-fetch` module, see https://github.com/Mermade/swagger2openapi/blob/828e4ac1634cf2f85f92e8538763eabd31ecbfcf/index.js#L1118-L1134

**Comment by MikeRalphson** [comment]
Included in v2.2.8 - thanks very much for the suggestion!
