### ISSUE TITLE
`env: node\r: No such file or directory` on macos

### ISSUE THREAD

**Issue by stiancognite** [Mermade/widdershins#49]
Trying to use widdershins on macos I get a `env: node\r: No such file or directory` error. I got around it by installing dos2unix (using brew) and then executing `dos2unix /usr/local/lib/node_modules/widdershins/widdershins.js`. Should this be a problem, or was there something specific to my system that required me to change the line endings?

**Comment by MikeRalphson** [comment]
Hi, @stiancognite did you install via npm, yarn or by cloning the git repository? If the latter, what is your git `core.autocrlf` setting set to (`git config core.autocrlf`)?

**Comment by stiancognite** [comment]
I tried installing it via npm after installing npm with nvm, and I tried installing it via npm after installing npm directly with brew - I got the same result.

**Comment by MikeRalphson** [comment]
Ok, that rules out `git` then. I'll see if there are any helpful settings so Windows line-endings are stripped when publishing to npm.

**Comment by MikeRalphson** [comment]
I've just fixed the line-endings in `widdershins.js` and republished as `v2.2.2` - please could you test this to see if it fixes things for you?

**Comment by stiancognite** [comment]
Yes, that works :)

**Comment by MikeRalphson** [comment]
Excellent, thanks for reporting and letting me know it's fixed.
