### ISSUE TITLE
Does 'AllOf' criteria is Considered?

### ISSUE THREAD

**Issue by saikrishnaradarapu** [Mermade/widdershins#5]
Because when I give any json with allOf criteria desired output is not coming..

**Comment by MikeRalphson** [comment]
Hi @saikrishnaradarapu, do you have an example of a schema object you can share? This is possibly due to a circular reference in your schema, or a bug/limitation in the OpenAPI-sampler module used to generate the schema examples...

**Comment by MikeRalphson** [comment]
It looks like `allOf` should be supported, but with a couple of limitations. Do you get any warning messages, i.e. the ones in [this piece of code](https://github.com/APIs-guru/openapi-sampler/blob/master/src/normalize.js) ?

**Comment by saikrishnaradarapu** [comment]
Yeah there is a problem with my schema object. The problem solved now thank you once again.

**Comment by MikeRalphson** [comment]
Thanks for letting me know.
