### ISSUE TITLE
user_template is not well defined

### ISSUE THREAD

**Issue by rb-engineer** [Mermade/widdershins#538]
**Describe the bug**
There's not much to say, I wanted to redefine `responses.def` template, and I followed the instructions that indicate I must copy parent and child, so I copied `main.dot` and `responses.def`, and it wasn't enough, didn't work

and I managed to find that `operation.dot` was also required to modify `responses.def`.

but `operation.dot` references a many files inside, so: 

> this is my custom templates folder
<img width="315" alt="image" src="https://user-images.githubusercontent.com/28882108/233154765-87277616-7a85-498b-ad9d-0205ab6c78a3.png">

this should be in the documentation, or at least show few more cases/examples of using `--user_templates`

thank you.

**To Reproduce**
1. Command-line: 
```
widdershins --language_tabs 'javascript:JavaScript' 'http:HTTP' --user_templates './documentation/templates' --summary documentation/openapi3.json -o documentation/slate/index.md
```

**Versions**:
- 18.15.0

**Comment by MikeRalphson** [comment]
We call this out in the README:

> This means that it is usually easiest to copy all .dot and .def files to your user templates directory so you don't skip a template or partial.
