### ISSUE TITLE
[Question] Replace Method Name from swagger operationId to summary. 

### ISSUE THREAD

**Issue by jmpascal** [Mermade/widdershins#57]
Hello,

I use widdershins to transform a swagger model to a slate compliant markdown files.
We discover that the swagger **operationId**  (like addPet, deletePet...) is used to create the method name  (in the left menu & middle page).

We would prefer to use swagger **summary** (Add a new Pet, Delete a Pet) field for this purpose. 

Is there a simple way to achieve this goal ? (By coding or by passing a specific parameter)

Thanks in advance.

PS: Thanks also for the current work.

**Comment by MikeRalphson** [comment]
Hi @jmpascal thanks for raising this issue.

In the impending rewrite, you should be able to adjust the TOC with user templates, but in the meantime I've made a quick change to add a `--summary` option (or `options.tocSummary` if you're using the programmatic API). It seems to work fine, but please let me know how you get on with it. It may need a little work to tweak the middle section?

Included in v2.2.6

**Comment by jmpascal** [comment]
Roooohhhh. Too Easy & Quick ! :-) 
That's a brilliant job and works perfectly with 2.2.6 !

There's still I think a little details to fix in the middle section.
<img width="212" alt="screen shot 2017-10-27 at 13 08 53" src="https://user-images.githubusercontent.com/792752/32101431-7556c700-bb18-11e7-8a00-110586437193.png">
I would rather not duplicating the summary as Title header & italic description.

It's purely cosmetic but evil is in the details ^^

**Comment by MikeRalphson** [comment]
Ok, so we should omit the summary if it's already been used as the TOC header?

**Comment by jmpascal** [comment]
Yeap that's my feeling.

**Comment by MikeRalphson** [comment]
Agreed, try v2.2.7!

**Comment by jmpascal** [comment]
and it's a wrap !

Looks perfect.

Thanks a lot for your solution & quick reaction !
