### ISSUE TITLE
Parameter passing broken 

### ISSUE THREAD

**Issue by davefp** [Mermade/widdershins#62]
My API spec is written in YAML. I have been unable to get the following to work:

`widdershins -y docs/openapi.yml docs/compiled.md`

It fails saying that it can't find the file `-y`.

Digging a bit deeper, it looks like parameter passing has been broken since 2.2.4. Version 2.2.3 works as intended

**Comment by MikeRalphson** [comment]
Many thanks for spotting this and reporting it. It should be fixed in v2.2.9 - in fact the `-y` switch is a no-op these days, ironically it's only there for backwards compatibility. You would need a `-o` in the above command-line though I think.

Please chase if any further problems.

**Comment by davefp** [comment]
Thanks for the quick fix!
