### ISSUE TITLE
RangeError when using widdershins with a new OpenApi v3 spec file

### ISSUE THREAD

**Issue by stiancognite** [Mermade/widdershins#65]
```
➜  api git:(swagger2) ✗ widdershins openapi.0.3.json
Compiling all doT templates...
Compiling authentication.dot to function
Compiling authentication_none.dot to function
Compiling code_http.dot to function
Compiling code_java.dot to function
Compiling code_javascript.dot to function
Compiling code_nodejs.dot to function
Compiling code_python.dot to function
Compiling code_ruby.dot to function
Compiling code_shell.dot to function
Compiling discovery.dot to function
Compiling footer.dot to function
Compiling heading_body_parameter.dot to function
Compiling heading_code_samples.dot to function
Compiling heading_example_responses.dot to function
Compiling heading_main.dot to function
Compiling parameters.dot to function
Compiling response_headers.dot to function
Compiling response_schema.dot to function
Compiling responses.dot to function
Compiling schema_header.dot to function
Compiling schema_properties.dot to function
Compiling schema_sample.dot to function
Compiling security.dot to function
/usr/local/lib/node_modules/widdershins/openapi3.js:761
            content += templates.schema_sample(data) + '\n';
                                                     ^

RangeError: Invalid string length
    at Object.convert (/usr/local/lib/node_modules/widdershins/openapi3.js:761:54)
    at Object.convert (/usr/local/lib/node_modules/widdershins/index.js:18:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/widdershins/widdershins.js:101:11)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
```

Is there something wrong with my openapi.json file? I'll attach it here: [openapi.0.3.json.zip](https://github.com/Mermade/widdershins/files/1470683/openapi.0.3.json.zip)

**Comment by MikeRalphson** [comment]
Are you able to test with the beta of widdershins v3.0.0 ? It's in the `v3.0` branch on github only at the moment. If it's easier I can see about releasing a beta on npm.

You (temporarily) need to add the `-x` switch to use the new templates etc.

In v3 the output completes, though some of the examples are very large due to deeply nested models. You can mitigate this by using the `--maxDepth` option.

```yaml
$ node widdershins.js -x test/issue65.json -o out/issue65b.md
Compiling all doT templates...
Loaded def authentication.def
Loaded def authentication_none.def
Loaded def callbacks.def
Loaded def debug.def
Loaded def discovery.def
Loaded def footer.def
Loaded def links.def
Loaded def parameters.def
Loaded def responses.def
Loaded def security.def
Compiling code_http.dot to function
Compiling code_java.dot to function
Compiling code_javascript.dot to function
Compiling code_nodejs.dot to function
Compiling code_python.dot to function
Compiling code_ruby.dot to function
Compiling code_shell.dot to function
Compiling main.dot to function
Compiling operation.dot to function
Compiling translations.dot to function
# sampler Maximum call stack size exceeded
............................................
```

**Comment by stiancognite** [comment]
You reply so fast! :)

Are there instructions on how I can build v3 locally somewhere? I'm afraid I'm not that familiar with the Javascript stack.

**Comment by MikeRalphson** [comment]
As to any problems with your definition, I can see a number of paths with `{project}` templated parameters, but no parameter array entry for them.

**Comment by stiancognite** [comment]
Sorry about that, I mean to replace `{project}` before posting the file.

**Comment by MikeRalphson** [comment]
You should be able to clone the repo, check out the `v3.0` branch and do `npm i` and things should just work. But the offer to release a beta on npm is still there. As to fast, I was looking at another issue on github at the time, so I saw the notification... And I'm actively looking out for test cases for v3. 😄

**Comment by stiancognite** [comment]
Sorry about the dumb question, but I ran `npm i` and it went fine (output was: `added 100 packages in 3.642s`). But how do I use the version that I built? `widdershins --version` stil says 2.2.4.

**Comment by MikeRalphson** [comment]
If you have widdershins installed globally, it may be picking up that version, but the other reason is I'd forgotten to update the version in `package.json`. 😨 

If you `node widdershins.js` in the checked-out directory it should use the local copy.

The output of `node widdershins --help` should have the following entries:

```
  --expandBody          Expand requestBody properties in parameters    [boolean]
  --headings            Levels of headings to expand in TOC[number] [default: 2]
  --resolve             Resolve external $refs                         [boolean]
  --summary             Use summary instead of operationId for TOC     [boolean]
  -e, --environment     Load config/override options from file          [string]
  -m, --maxDepth        Maximum depth for schema examples          [default: 10]
  -x, --experimental    Use experimental template mode                 [boolean]
```

**Comment by stiancognite** [comment]
I tried this, but got 2.2.9:
```
➜  widdershins git:(v3.0) npm i -g
/usr/local/bin/widdershins -> /usr/local/lib/node_modules/widdershins/widdershins.js
+ widdershins@2.2.9
removed 4 packages and updated 5 packages in 1.165s
➜  widdershins git:(v3.0) ✗ widdershins --version
2.2.9
```
That seems to be right though, because:
```
➜  api git:(swagger2) ✗ widdershins -x openapi.0.3.json --maxDepth 2
Compiling all doT templates...
Loaded def authentication.def
Loaded def authentication_none.def
Loaded def callbacks.def
Loaded def debug.def
Loaded def discovery.def
Loaded def footer.def
Loaded def links.def
Loaded def parameters.def
Loaded def responses.def
Loaded def security.def
Compiling code_http.dot to function
Compiling code_java.dot to function
Compiling code_javascript.dot to function
Compiling code_nodejs.dot to function
Compiling code_python.dot to function
Compiling code_ruby.dot to function
Compiling code_shell.dot to function
Compiling main.dot to function
Compiling operation.dot to function
Compiling translations.dot to function
# sampler Maximum call stack size exceeded
........................
```
and then it seems to work :)

**Comment by MikeRalphson** [comment]
Yes, if you're seeing `Loaded def` and lines of `...` instead of repeated sampler errors you're definitely running v3.0! I'll fix the version string in a mo. Don't forget to play about with `--maxDepth` to get a reasonably-sized output file.

And thanks for testing it!

**Comment by MikeRalphson** [comment]
> Should I be concerned about that # sampler Maximum call stack size exceeded

That just means you have one or more circular references in your schema models. Widdershins now tries a number of back-off strategies to try and get an example generated. One of which is to replace circular references with `[Circular]` (which slightly unfortunately comes out as `null` in the generated example).

Probably the best option is to add a real-life `example` property to the OpenAPI 3.0 definition which will override the generated one(s).

**Comment by stiancognite** [comment]
Thank you for the great help as always!:)

**Comment by stiancognite** [comment]
It would actually be nice with a beta version on npm because then I could use that in our CI pipeline witout having to add a git clone && npm i step. :) Or do you have an approximate idea of when v3 will be released?

**Comment by MikeRalphson** [comment]
No problem, will just check on marking a release as a beta, then ping you when it's there.

**Comment by MikeRalphson** [comment]
Looks like that worked, you'll need to ensure you install `widdershins@3.0.0-beta0.0` for this specific version or `widdershins@beta` to track this and any future betas.

**Comment by stiancognite** [comment]
I tried installing that but got this:
```
➜  ~ npm install -g widdershins@3.0.0-beta0.0
/usr/local/bin/widdershins -> /usr/local/lib/node_modules/widdershins/widdershins.js
+ widdershins@3.0.0-beta0.0
updated 2 packages in 4.64s
➜  ~ widdershins --version
module.js:529
    throw err;
    ^

Error: Cannot find module 'js-yaml'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/widdershins/widdershins.js:8:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```
Is there something wrong with my system?

**Comment by MikeRalphson** [comment]
Possibly... what version of Node.js and npm are you running?

**Comment by stiancognite** [comment]
```
➜  api git:(swagger2) node --version
v8.6.0
➜  api git:(swagger2) npm --version
5.5.1
```

**Comment by MikeRalphson** [comment]
Hmm, I'd hope they'd be ok. I'll try installing it on another machine.

**Comment by stiancognite** [comment]
Should I try to upgrade node?

**Comment by MikeRalphson** [comment]
No, I'm only on v8.7.0 and we test on v4.x and v6.x as well. I suspect something is wrong in the `package-lock.json` but I need to investigate what.

**Comment by stiancognite** [comment]
Thanks! Let me know if there's anything I can do.

**Comment by MikeRalphson** [comment]
Ok, I've tried installing on another machine and `widdershins --version` works ok. Can you try blowing away the `node_modules` folder (probably `/usr/local/lib/node_modules/widdershins/node_modules/`) and reinstalling?

**Comment by stiancognite** [comment]
That worked! Thanks :)
