### ISSUE TITLE
A new parameter 'body' gets added for hash type params

### ISSUE THREAD

**Issue by arparthasarathi** [Mermade/widdershins#67]
Specs
  * Swagger 2.0
  * Widdershins installation from the branch v3.0

I am using parameters of type **hash** for our APIs. Swagger generates the JSON as given below

`
"paths":{"/betaweb/users/sign_in":{"post":{"description":"User Authentication API","produces":["application/json"],"consumes":["application/json"],"parameters":[{"in":"formData","name":"user[email]","description":"User email","type":"string","required":false},{"in":"formData","name":"user[username]","type":"string","required":false},{"in":"formData","name":"user[password]","description":"User Password","type":"string","required":true}],"responses":{"201":{"description":"Created"},"422":{"description":"Invalid Login Credentials"}},"tags":["users"],"operationId":"User Authentication API"}},
`

But my Slate Markdown adds a parameter **body** to my request as below.

![screen shot 2017-11-15 at 3 01 41 pm](https://user-images.githubusercontent.com/5359707/32828727-f4f2c7aa-ca15-11e7-961f-f87d62aeb0a0.png)

I couldn't figure out to remove the **body** parameter.

And also, the **password** parameter required is set to **true** in the Swagger JSON. But the in the documentation, required field for **password** is set to **false**

**Comment by MikeRalphson** [comment]
This is an artifact of the way the `formData` parameters are internally converted into the `requestBody` structure used by OpenAPI 3.0.

I'll add an option to omit the enclosing (fake) `body` parameter.

**Comment by arparthasarathi** [comment]
Is there any way that I could prevent the enclosing from my side?

**Comment by MikeRalphson** [comment]
You can patch `openapix.js` in function `fakeBodyParameter` and comment-out the first instance of the following line:

```js
bodyParams.push(param);
```

It should be line 275.

**Comment by arparthasarathi** [comment]
Perfect ! Thanks for the patch. Works seamlessly. You are awesome Mike, saving us a lots of time.

A quick question, why is that am getting the symbol **>>** before the parameters? Not a pressing issues, just for getting a deeper understanding of how the parser works.

![screen shot 2017-11-15 at 5 19 15 pm](https://user-images.githubusercontent.com/5359707/32834670-630a8616-ca29-11e7-80a5-413615462ffd.png)

**Comment by MikeRalphson** [comment]
That's because it's showing a nested properties under the object that we've just hidden.

If you change the offset 0 to -1 on the following line, they should go away:

```js
let props = common.schemaToArray(data.bodyParameter.schema,0,{trim:true},data);
```

Line 278. Thanks for testing my changes I haven't even written yet!

**Comment by arparthasarathi** [comment]
Awesome! Thanks for that :) 

Mike, am also facing an issue with the **required** field as said above. If you take a look at the first screen shot, the parameter **password** is mentioned as required in the Swagger JSON but in the markdown, the field is set to false. And in the screenshot that I have added in the subsequent comment, every field is a required one. But only the email field is set as required.

Is this an issue or am I doing anything wrong?

**Comment by MikeRalphson** [comment]
> Mike, am also facing an issue with the required field as said above.

This was a bug in the OpenAPI 2.0 to 3.0 converter. When the next beta of widdershins is released (hopefully later today) it will have the updated converter dependency.

Thanks again for the testing and the bug reports!

**Comment by MikeRalphson** [comment]
Apologies for the delay, widdershins@3.0.0-beta0.1 has just been released.

**Comment by MikeRalphson** [comment]
Widdershins v3.0.0 has just been released.

**Comment by arparthasarathi** [comment]
Thanks a lot for the update Mike!
