### ISSUE TITLE
[Questions] OpenAPI - Parameters & Schemas sections

### ISSUE THREAD

**Issue by jmpascal** [Mermade/widdershins#68]
Aloah,

I currently tweak my OpenAPi/slate integration with widdershins and I encounter a special use case.
By using default command like
`widdershins --summary -y apiName.yaml index.html.md`

I have this result where FormRequest (Body Parameter of my Method) is present with the schema associated inside the Parameters section (See also the >> character associated). Notice there's also a Schemas section in my main menu.
![screen shot 2017-11-20 at 16 01 34](https://user-images.githubusercontent.com/792752/33024716-237f0a9e-ce0c-11e7-88a3-e4ac7955e954.png)

When I use the same command line with --noschema parameter like
`widdershins --summary --noschema -y apiName.yaml index.html.md`

I obtain this result. The parameters section only contains the FormRequest body parameter. 
Schemas section in my main menu is also not present. It makes the hyperlink to FormRequest impossible to use.
![screen shot 2017-11-20 at 15 58 53](https://user-images.githubusercontent.com/792752/33024569-bea23d12-ce0b-11e7-9d15-4bb362bfb64d.png)

My question is simple. 

**Is it possible to have the Schemas sections available 
AND 
not displaying the inline Parameters  ( >> parameters) ?**

I would prefer my user to click the FormRequest hyperlink to have access directly to the parameter schema instead of having it displaying inside the parameters section with the >> symbol.

Thanks in advance.

**Comment by MikeRalphson** [comment]
I think in Widdershins v3.0 (beta) the default options will give you what you want. Body parameters are no longer expanded (unless `--expandBody` is set) and schemas are always included unless the `main` template is overridden. You can install `widdershins@beta` to try it out.

**Comment by jmpascal** [comment]
Yeah I confirm it's the idea I'm looking for. (even if the Schemas Info are undefined for the moment but It's a beta version cf screenshot).

![screen shot 2017-11-20 at 17 06 39](https://user-images.githubusercontent.com/792752/33028124-4502d78c-ce15-11e7-8c11-a765ce48a2a5.png)

I will look at it when 3.0 will be released in this case.

Thanks for the info.

**Comment by MikeRalphson** [comment]
Could you share your definition of `FormRequest` and let me know if you have overridden the default template? It shouldn't be coming out with `undefined` anywhere...

**Comment by jmpascal** [comment]
For sure. Everything is available here: 
https://github.com/flowable/flowable-engine/blob/master/docs/public-api/references/swagger/form/flowable-swagger-form.yaml

**Comment by MikeRalphson** [comment]
Thanks, have confirmed no `undefined` is output using the stock templates.
