### ISSUE TITLE
No binary created when installed via npm or yarn

### ISSUE THREAD

**Issue by kjg** [Mermade/widdershins#7]
I tried installing both via npm and yarn, but neither install produced a runnable widdershins binary that I could run

**Comment by MikeRalphson** [comment]
@kjg Thanks for reporting this. I'll take a look. For now you should be able to `node widdershins.js` - possibly supplying the path to the directory it's installed in.

**Comment by MikeRalphson** [comment]
@kjg I've just published v1.0.8 which specifies a binary, can you see if that fixes it for you? My setup is a bit non-standard.

**Comment by kjg** [comment]
v1.0.8 works. Thanks!
