### ISSUE TITLE
Custom parameters.dot not being used?

### ISSUE THREAD

**Issue by stiancognite** [Mermade/widdershins#70]
I'm using widdershins like this: `widdershins -x swagger/openapi.json --maxDepth 5 -o ../slate-fork/source/index.html.md -u swagger/widdershins-templates`. The contents of `parameters.dot` which lies in the `widdershins-templates` folder is:
```
### Parameters

Parameter|In|Type|Required|Description|Restrictions
---|---|---|---|---|---|
{{~ data.parameters :p}}{{=p.name}}|{{=p.in}}|{{=p.type}}|{{=p.required}}|{{=p.shortDesc}}|{{? p.schema && p.schema.maximum && p.schema.minimum}}Min/Max: {{=p.schema.minimum}}/{{=p.schema.maximum}}{{?? p.schema && p.schema.maximum}}Max: {{=p.schema.maximum}}{{?? p.schema && p.schema.minimum}}Min: {{=p.schema.minimum}}{{?? p.schema && p.schema.enum}}{{=p.schema.enum}}{{??}}N/A{{?}}
{{~}}

{{? data.enums.length}}
#### Enumerated Values

|Parameter|Value|
|---|---|
{{~ data.enums :e}}{{=e.name}}|{{=e.value}}|
{{~}}
{{?}}
```
But my documentation ends up looking like this:
![screen shot 2017-11-21 at 15 42 08](https://user-images.githubusercontent.com/32162187/33078321-9361760a-ced2-11e7-97e6-9188ad91e92c.png)

where I would expect to have an additional column on the right, named `Restrictions`. (As I currently have here: http://doc.cognitedata.com/#postassets.)

Are you able to see what's going wrong?

[Archive.zip with openapi.json and the templates folder](https://github.com/Mermade/widdershins/files/1491732/Archive.zip).

**Comment by MikeRalphson** [comment]
`parameters.dot` has become `parameters.def` in v3.0 (it's an included partial, not a template on it's own any more). If you copy `parameters.def` from `templates/openapix/` to your custom templates directory, and add in your restrictions column logic, it should work.

If not... try copying in `operation.dot` (no changes would be needed) as well, in case the parent template is required.

**Comment by stiancognite** [comment]
Thanks! I had to copy over the parent template as well and then it worked :)

**Comment by MikeRalphson** [comment]
Thanks - I'll add that to the README.
