### ISSUE TITLE
Seeing many 'undefined'  using widdershins@3.0.0-beta0.2

### ISSUE THREAD

**Issue by stiancognite** [Mermade/widdershins#71]
Just to check where they came from I overrode `operation.dot` like this:
```
## {{= data.operationUniqueName}}

{{ data.methodUpper = data.method.verb.toUpperCase(); }}
{{ data.url = data.baseUrl + data.method.path; }}
{{ data.parameters = data.operation.parameters; }}
{{ data.enums = []; }}
{{ data.utils.fakeProdCons(data); }}
{{ data.utils.fakeBodyParameter(data); }}
{{ data.utils.mergePathParameters(data); }}
{{ data.utils.getParameters(data); }}

{{? data.options.codeSamples || data.operation["x-code-samples"] }}
> Code samples

{{= data.utils.getCodeSamples(data) }}
{{?}}

`{{= data.methodUpper}} {{=data.method.path}}`

{{? data.operation.summary && !data.options.tocSummary}}*{{= data.operation.summary }}*{{?}}

{{? data.operation.description}}{{= data.operation.description }}{{?}}

{{? data.operation.requestBody}}
> Body parameter

{{= data.utils.getBodyParameterExamples(data) }}
{{?}}

{{? data.parameters && data.parameters.length }}
{{#def.parameters}}
{{?}}

debug1
{{#def.responses}}
debug2

debug3
{{#def.callbacks}}
debug4

debug5
{{ data.security = data.operation.security ? data.operation.security : data.api.security; }}
{{? data.security && data.security.length }}
{{#def.authentication}}
{{??}}
{{#def.authentication_none}}
{{?}}
debug6
```

This results in:
![screen shot 2017-11-22 at 10 12 54](https://user-images.githubusercontent.com/32162187/33118947-bc0b2812-cf6d-11e7-858f-5ae706fcdd8a.png)

Here are openapi.json and my templates: [Archive.zip](https://github.com/Mermade/widdershins/files/1495271/Archive.zip). Could you take a look and advice me on how I can avoid those `undefined` outputs?

**Comment by MikeRalphson** [comment]
Can you try coping the remaining `.def` files from the `templates/openapix` directory? It appears that `.def` files are included by the template at compile time, and it's not finding the child partials (`'def`s) when the template `.dot` is overridden.

An option (for me) is changing all the `.def`s back into `.dot`s and calling them as functions...

**Comment by stiancognite** [comment]
Copying the remaining `.def` files worked! Thanks again :)

**Comment by MikeRalphson** [comment]
No, thanks for testing (and sorry for the teething troubles with the beta). Again, I'll update the README to make this clear.
