### ISSUE TITLE
Override authentication.def message to show name and not type? Using widdershins@3.0.0-beta0.2

### ISSUE THREAD

**Issue by stiancognite** [Mermade/widdershins#72]
I have two securityschemes that both are of type apiKey, but they have different names. I would like to change `authentication.def` to not show the type, like it does originally, but show the name. How could I do this? I'm trying to avoid this:
![screen shot 2017-11-22 at 11 13 03](https://user-images.githubusercontent.com/32162187/33121803-22b609c6-cf76-11e7-863e-718965eb9fac.png)
I had the same problem with the authentication info in the header, but that I solved by changing `security.def` like this:
```
{{? sd.type == 'apiKey' }}
* {{=sd.name}}
    - Parameter Name: **{{=sd.name}}**, in: {{=sd.in}}. {{=sd.description || ''}}
```
instead of the original:
```
{{? sd.type == 'apiKey' }}
* API Key
    - Parameter Name: **{{=sd.name}}**, in: {{=sd.in}}. {{=sd.description || ''}}
```
There it was just a matter of printing another variable. But as `authentication.def` calls a method (`data.utils.getAuthenticationStr(data)`), how can I make the same change there?

**Comment by MikeRalphson** [comment]
This is a really good question. Widdershins should definitely show the name of the securityScheme not just the type.

I've added this to the `getAuthenticationStr` function. It's included in widdershins@3.0.0-beta0.3

Answering your question re: the `data.utils.getAuthenticationStr` function: more generally, the properties of the `data` object, including functions, can be overridden by using the `templateCallback` feature on the `main` template in the `pre` stage.

**Comment by stiancognite** [comment]
Thanks. The new version took care of it :)

**Comment by stiancognite** [comment]
And that was the last "issue" I had to get through before upgrading our API to use OpenApi v3 :) http://doc.cognitedata.com/

Thank you again for all the help, Mike!

**Comment by MikeRalphson** [comment]
No problem, you've done some great testing! Would it be ok if I added a link to your documentation to the 'Widdershins in the wild' section of the readme? Are you using Shins too (it's very hard to tell!).

**Comment by stiancognite** [comment]
Sure! We're using Slate. Would probably have chosen Shins if we were to start now. I don't see any wins by changing over to Shins atm so staying with Slate for now :)
