### ISSUE TITLE
Response class that is empty gets a field called "anonymous"

### ISSUE THREAD

**Issue by stiancognite** [Mermade/widdershins#73]
![screen shot 2017-11-27 at 10 11 54](https://user-images.githubusercontent.com/32162187/33258957-8ba26130-d35b-11e7-9fc7-15026a107de6.png)

The class looks like this in openapi.json:
```
      "EmptyResponse" : {
        "type" : "object"
      }
```
and I would like to avoid that "anonymous" field that appears after running `widdershins -x swagger/openapi.json --maxDepth 5 -o index.html.md -u swagger/widdershins-templates`. Is there a way to do that?

openapi.json and the templates used: 
[Archive.zip](https://github.com/Mermade/widdershins/files/1505218/Archive.zip)

```
➜  widdershins --version
3.0.0-beta0.3
```

**Comment by stiancognite** [comment]
Yeah, that's what I was expecting :)

**Comment by MikeRalphson** [comment]
The workaround for the sample generator and primitive responses has been tweaked to remove the anonymous container object in widdershins v3.0.0-beta0.4 

Thanks.

**Comment by stiancognite** [comment]
Works as I expected! Thanks:)
