### ISSUE TITLE
Component/schema/references odd behaviour

### ISSUE THREAD

**Issue by trev** [Mermade/widdershins#75]
Given the following partial openapi3 YAML:

```
components:
  schemas:
    Terms:
      title: Agreement terms
      required:
        - per_payout
        - per_frequency
      type: object
      description: Terms
      properties:
        per_payout:
          $ref: '#/components/schemas/PerPayout'
        per_frequency:
          $ref: '#/components/schemas/PerFrequency'
    PerPayout:
      title: Per payout terms
      type: object
      properties:
        min_amount:
          type: number
          nullable: true
          description: ''
          example: 0
        max_amount:
          type: number
          nullable: true
          description: ''
          example: 10000
    PerFrequency:
      title: Per frequency terms
      type: object
      properties:
        days:
          type: number
          nullable: true
          description: ''
          example: 7
        max_amount:
          type: number
          nullable: true
          description: ''
          example: 1000000
```

If I run Widdershins with `--expandBody` for an endpoint that has `$ref: '#/components/schemas/Terms` the `PerFrequency.max_amount` does not get generated.
If I rename the `PerFrequency.max_amount` to anything else, it's totally fine.

Looks like it's has to do with the fact that the `PerPayout` schema also has the `max_amount`.

I'm using the latest Widdershins. Thanks for your work!

**Comment by MikeRalphson** [comment]
This was due to the rule that OpenAPI definitions can't have multiple parameters with identical `name` and `in` properties. This was mistakenly being applied to the 'fake' `body` parameters.

Fixed in v3.0.1. Many thanks for taking the time to report this.
