### ISSUE TITLE
Feature request: Add option to generate one markdown file per swagger tag

### ISSUE THREAD

**Issue by geld0r** [Mermade/widdershins#82]
Widdershins seems to assume that you have only one Swagger/OpenApi-File which contains the whole API specification and generates a single markdown file from that.

It would be nice to be able to split the result into multiple files (which can then be referenced via the Slate "includes" option) as this would easy maintainability and allow to reuse the generated markdown in other contexts. Also it may help in cases where the final markdown file should contain manually created includes (i.e. content that is not originally maintained in the swagger/OpenApi specification).

What I have in mind is an additional option, that for example results in the generation of one markdown file per swagger-tag (https://swagger.io/docs/specification/grouping-operations-with-tags/).
For example if you have:

```paths:
  /pet/findByStatus:
    get:
      summary: Finds pets by Status
      tags:
        - cat
      ...
  /pet:
    post:
      summary: Adds a new pet to the store
      tags:
        - mouse
      ...
```

This would generate three files:
- One main "index.md" which has includes for the generated files "cat.md" and "mouse.md".
- The file "cat.md"
- The file "mouse.md"

Maybe there are also other criteria by which the content should be split, but using tags would fit our use case.

**Comment by MikeRalphson** [comment]
I can foresee some issues / limitations with this idea:

* Slate only allows include files at the end of the main markdown file
* Where should shared models/schemas be output, in another separate file?
* How does splitting the markdown up help with including external content?
* How does this aid maintainability, if the content needs to be regenerated whenever the API definition changes?

**Comment by MikeRalphson** [comment]
Workaround - you could add html comments to the default templates which would allow you to split up the output markdown into multiple files (using a tool such as awk).

**Comment by geld0r** [comment]
Ok, good points.

Splitting into multiple files would (hopefully) allow to easier find places that require manual changes. You are right though, this would only really help if it was also possible to only partially regenerate documentation (e.g. only "mouse"-tag).

To clarify the underlying use case: Not everything that should be present in the final documentation can be generated directly from swagger (e.g. introduction, how to receive an api key, terminology and other things that are not specified by swagger). These are things that have to be manually edited/extended in the markdown after it has been generated. After regenerating it, the previously done manual changes would have to be redone/merged - this is not nice. It would be good if the generator would somehow ease this workflow, either by allowing includes or maybe also by allowing to exclude certain parts to be regenerated. Maybe this doesn't necessarily require an adjustment to the generator but can be covered by an improved workflow on our side.

**Comment by MikeRalphson** [comment]
From the shins readme:

Shins supports AsciiDoc include::filename[] syntax as well as !INCLUDE filename from markdown-pp

Although this again would mean altering the stock templates.

**Comment by geld0r** [comment]
I would assume that this would similarly for Slate? I.e. we would use custom templates in our workflows that only differ from the stock templates by having the additional include(s) (e.g. in the top)?

Let me try that out and report back.

**Comment by MikeRalphson** [comment]
Ping @geld0r did you have any luck?

**Comment by geld0r** [comment]
Sorry, this got lost. Yes I did try this out and added includes in "main.dot", like this:

`<%= partial "includes/yourFileName.md" %>
`
This makes use of [Middleman partials](https://middlemanapp.com/basics/partials/). Our source file is now a index.html.md.erb  (yes, really), but includes work this way. The downisde is that (as you said) we had to override the stock templates. This makes version updates quite tricky as one has to take care of merging the changes. Apart from that, this solution works fine.

If you don't plan any direct support for includes (for the reasons you listed above), this issue can be closed from my side as the workaround works.

**Comment by MikeRalphson** [comment]
> If you don't plan any direct support for includes (for the reasons you listed above), this issue can be closed from my side as the workaround works.

I'm not opposed to adding a third method (!) for includes, but I don't think I can see how they can be incorporated in the stock templates when they're not known in advance.

Feel free to re-open that discussion at any time, but let's close on the idea of generating multiple `.md` files per tag for now.
