### ISSUE TITLE
Documentation required: What does the "headings" option do

### ISSUE THREAD

**Issue by geld0r** [Mermade/widdershins#83]
The documentation for widdershins mentions the `headings` option.
When changing this, the only effect on the generated markdown seems to be that the heading level is added to the (slate) header.

This doesn't seem to have any effect on the generated slate documentation though.

What I expected is, that this changes the menu behavior in slate, i.e. allows deeper nesting of the menu entries (TOC).

Example: 
Heading level 2:

```
- Authorization
- Kittens
  - getKitten
  - addKitten
```

Heading level 3:

```
- Authorization
- Pets
  - Kittens
    - getKitten
    - addKitten
  - Puppies
    - getPuppy
    - addPuppy
```

In the dot templates file I can see though, that the html headings (as well as markdown headings) that are generated are in fact hardcoded while slate would expect them to differ in order to properly render the menu nesting.

Is the intended effect of the "headings" option something different?

**Comment by MikeRalphson** [comment]
The `headings` option is there to support `shins` (a nodejs port of Slate) which does support, out of the box, configurable levels of header nesting. Slate does not support this without [some hacking](https://github.com/lord/slate/wiki/Deeper-Nesting).

The README should probably be updated to make this clear. Thanks.

**Comment by MikeRalphson** [comment]
`README.md` updated, thanks for pointing this out.

**Comment by geld0r** [comment]
Thanks for the clarification.

**Comment by ckatta** [comment]
hi does anyone having idea on how to add a header in widdershins template

**Comment by MikeRalphson** [comment]
What kind of header?
