### ISSUE TITLE
Add Golang support for OpenAPI

### ISSUE THREAD

**Issue by luigi-riefolo** [Mermade/widdershins#89]
Hi, I've just created a dot file for Golang. Please have a look and let me know whether it can be included.

```
package main

import (
    "bytes"
    "net/http"
)

func main() {

{{?data.allHeaders.length}}
    headers := map[string][]string{
        {{~data.allHeaders :p:index}}"{{=p.name}}": []string{"{{=p.exampleValues.object}}"},
        {{?index < data.allHeaders.length-1}}{{?}}{{?index == data.allHeaders.length-1 && data.securityDefinitions && data.securityDefinitions[0].in == 'header'}}},
        {{?}}{{~}}{{?data.securityDefinitions && data.securityDefinitions[0].in == 'header' && data.securityDefinitions[0].type == 'apiKey'}}"Authorization": []string{"Bearer xxxxxx.yyyyyyy.zzzzzz"},{{?}}{{?}}
    }

    data := bytes.NewBuffer([]byte{jsonReq})
    req, err := http.NewRequest("{{=data.methodUpper}}", "{{=data.url}}", data)
    req.Header = headers

    client := &http.Client{}
    resp, err := client.Do(req)
    // ...
}
```

**Comment by MikeRalphson** [comment]
Many thanks for the PR.

Where the security definition doesn't match your test, I'm seeing a trailing comma after the headers:

```go
    headers := map[string][]string{
        "Content-Type": []string{"application/json"},


    }
```

Is that easy to fix, or ok in Go? Though we may have another way of handling the `Authorization` header soon, see #76 

Thanks again.

**Comment by luigi-riefolo** [comment]
@MikeRalphson it's totally fine in Go, actually it's mandatory if the ending brace is not on the same line as the last entry.
I'll deal with the `Authorization` header as soon as you release the updates.
Could you please tell me how to open a relative PR? Do I need any authorization?

**Comment by MikeRalphson** [comment]
I'm going to close this now, but feel free to chase this issue or raise further PRs to update the Go code template. Thanks again.
