### ISSUE TITLE
Dependency on Git repo for safe-json-stringify package

### ISSUE THREAD

**Issue by simondean** [Mermade/widdershins#91]
Hi. The safe-json-stringify dependency is current referencing the GitHub repo https://github.com/MikeRalphson/safe-json-stringify . Would it be possible to replace the dependency with a NPM package. I’m not able to use widdershins at the moment due to the Git repo dependency. Thanks!

**Comment by MikeRalphson** [comment]
I will try and get the change in my fork accepted upstream with the official package.

**Comment by MikeRalphson** [comment]
https://github.com/debitoor/safe-json-stringify/pull/7

**Comment by MikeRalphson** [comment]
Resolved in widdershins `v3.4.1`. Thanks for your patience.
