### ISSUE TITLE
Content type parsing too strict for json & utf-8

### ISSUE THREAD

**Issue by geld0r** [Mermade/widdershins#92]
Currently widdershins expects exactly the following format when the content type is json with utf-8:
`var jsonContentTypes = ['application/json; charset=utf-8', ...]'`

Other applications (e.g. Springfox which brings Swagger support to Spring projects) write the following content type (note that there is no space after the semicolon and uppercase utf-8):
`application/json;charset=UTF-8`

This results in the content type not being recognized by widdershins and code examples not being shown. Could the parsing be made more robust to accept both ways of formatting?

**Comment by MikeRalphson** [comment]
Thanks for the report. Puts regex socks on...

**Comment by MikeRalphson** [comment]
Tests added to hopefully ensure no unintended changes in functionality.

Released in v3.0.7 please let me know if any problems, and thanks again for the report.

**Comment by geld0r** [comment]
Awesome, thanks for the very fast turnaround time!
Just updated and verified this to be working as expected!

**Comment by MikeRalphson** [comment]
Thanks for confirming!
